// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package daemon

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockdaemonActionRunner creates a new instance of mockdaemonActionRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdaemonActionRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdaemonActionRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockdaemonActionRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockdaemonActionRunner is an autogenerated mock type for the daemonActionRunner type
type mockdaemonActionRunner struct {
	mock.Mock
}

type mockdaemonActionRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdaemonActionRunner) EXPECT() *mockdaemonActionRunner_Expecter {
	return &mockdaemonActionRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type mockdaemonActionRunner
func (_mock *mockdaemonActionRunner) Run(daemonActionRequestMoqParam daemonActionRequest) error {
	ret := _mock.Called(daemonActionRequestMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(daemonActionRequest) error); ok {
		r0 = returnFunc(daemonActionRequestMoqParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdaemonActionRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockdaemonActionRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - daemonActionRequestMoqParam daemonActionRequest
func (_e *mockdaemonActionRunner_Expecter) Run(daemonActionRequestMoqParam any) *mockdaemonActionRunner_Run_Call {
	return &mockdaemonActionRunner_Run_Call{Call: _e.mock.On("Run", daemonActionRequestMoqParam)}
}

func (_c *mockdaemonActionRunner_Run_Call) Run(run func(daemonActionRequestMoqParam daemonActionRequest)) *mockdaemonActionRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 daemonActionRequest
		if args[0] != nil {
			arg0 = args[0].(daemonActionRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdaemonActionRunner_Run_Call) Return(err error) *mockdaemonActionRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdaemonActionRunner_Run_Call) RunAndReturn(run func(daemonActionRequestMoqParam daemonActionRequest) error) *mockdaemonActionRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
