// Terminal I/O, UI fences, and bounded preview viewports.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: terminal.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ViewContext is the committed boundary of one output state.
type ViewContext struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Publication   uint64                  `protobuf:"varint,1,opt,name=publication,proto3" json:"publication,omitempty"`
	Route         *CommittedRouteIdentity `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	TabId         string                  `protobuf:"bytes,3,opt,name=tab_id,json=tabId,proto3" json:"tab_id,omitempty"`
	FocusedPaneId string                  `protobuf:"bytes,4,opt,name=focused_pane_id,json=focusedPaneId,proto3" json:"focused_pane_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewContext) Reset() {
	*x = ViewContext{}
	mi := &file_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewContext) ProtoMessage() {}

func (x *ViewContext) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewContext.ProtoReflect.Descriptor instead.
func (*ViewContext) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *ViewContext) GetPublication() uint64 {
	if x != nil {
		return x.Publication
	}
	return 0
}

func (x *ViewContext) GetRoute() *CommittedRouteIdentity {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *ViewContext) GetTabId() string {
	if x != nil {
		return x.TabId
	}
	return ""
}

func (x *ViewContext) GetFocusedPaneId() string {
	if x != nil {
		return x.FocusedPaneId
	}
	return ""
}

// Output is one terminal state. Terminal data uses the explicit encoding
// enum below; converters compress only full snapshots at the frozen
// threshold and only when smaller.
type Output struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Epoch        uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Base         uint64                 `protobuf:"varint,2,opt,name=base,proto3" json:"base,omitempty"`
	NewState     uint64                 `protobuf:"varint,3,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Echo         uint64                 `protobuf:"varint,4,opt,name=echo,proto3" json:"echo,omitempty"`
	ViewRevision uint64                 `protobuf:"varint,5,opt,name=view_revision,json=viewRevision,proto3" json:"view_revision,omitempty"`
	Cols         uint32                 `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows         uint32                 `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	Full         bool                   `protobuf:"varint,8,opt,name=full,proto3" json:"full,omitempty"`
	Context      *ViewContext           `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"` // optional pointer
	// Closed encoding taxonomy: 0 = raw, 1 = zlib (full snapshots only).
	Encoding           uint32 `protobuf:"varint,10,opt,name=encoding,proto3" json:"encoding,omitempty"`
	UncompressedLength uint64 `protobuf:"varint,11,opt,name=uncompressed_length,json=uncompressedLength,proto3" json:"uncompressed_length,omitempty"`
	Data               []byte `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Output) GetBase() uint64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *Output) GetNewState() uint64 {
	if x != nil {
		return x.NewState
	}
	return 0
}

func (x *Output) GetEcho() uint64 {
	if x != nil {
		return x.Echo
	}
	return 0
}

func (x *Output) GetViewRevision() uint64 {
	if x != nil {
		return x.ViewRevision
	}
	return 0
}

func (x *Output) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Output) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Output) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *Output) GetContext() *ViewContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Output) GetEncoding() uint32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

func (x *Output) GetUncompressedLength() uint64 {
	if x != nil {
		return x.UncompressedLength
	}
	return 0
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ack cumulatively acknowledges one epoch.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	State         uint64                 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Ack) GetState() uint64 {
	if x != nil {
		return x.State
	}
	return 0
}

// Input carries client keystrokes and pastes.
type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputSeq      uint64                 `protobuf:"varint,1,opt,name=input_seq,json=inputSeq,proto3" json:"input_seq,omitempty"`
	ActionId      uint64                 `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *Input) GetInputSeq() uint64 {
	if x != nil {
		return x.InputSeq
	}
	return 0
}

func (x *Input) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *Input) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Resize carries a geometry claim.
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	PixelWidth    uint32                 `protobuf:"varint,3,opt,name=pixel_width,json=pixelWidth,proto3" json:"pixel_width,omitempty"`
	PixelHeight   uint32                 `protobuf:"varint,4,opt,name=pixel_height,json=pixelHeight,proto3" json:"pixel_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{4}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetPixelWidth() uint32 {
	if x != nil {
		return x.PixelWidth
	}
	return 0
}

func (x *Resize) GetPixelHeight() uint32 {
	if x != nil {
		return x.PixelHeight
	}
	return 0
}

// Theme carries the 57-byte fixed terminal theme block field by field.
type Theme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasForeground bool                   `protobuf:"varint,1,opt,name=has_foreground,json=hasForeground,proto3" json:"has_foreground,omitempty"`
	Foreground    *RGB                   `protobuf:"bytes,2,opt,name=foreground,proto3" json:"foreground,omitempty"`
	HasBackground bool                   `protobuf:"varint,3,opt,name=has_background,json=hasBackground,proto3" json:"has_background,omitempty"`
	Background    *RGB                   `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
	TrueColor     bool                   `protobuf:"varint,5,opt,name=true_color,json=trueColor,proto3" json:"true_color,omitempty"`
	SchemeKnown   bool                   `protobuf:"varint,6,opt,name=scheme_known,json=schemeKnown,proto3" json:"scheme_known,omitempty"`
	Light         bool                   `protobuf:"varint,7,opt,name=light,proto3" json:"light,omitempty"`
	PaletteKnown  uint32                 `protobuf:"varint,8,opt,name=palette_known,json=paletteKnown,proto3" json:"palette_known,omitempty"`
	Palette       []*RGB                 `protobuf:"bytes,9,rep,name=palette,proto3" json:"palette,omitempty"` // exactly 16 entries
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theme) Reset() {
	*x = Theme{}
	mi := &file_terminal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{5}
}

func (x *Theme) GetHasForeground() bool {
	if x != nil {
		return x.HasForeground
	}
	return false
}

func (x *Theme) GetForeground() *RGB {
	if x != nil {
		return x.Foreground
	}
	return nil
}

func (x *Theme) GetHasBackground() bool {
	if x != nil {
		return x.HasBackground
	}
	return false
}

func (x *Theme) GetBackground() *RGB {
	if x != nil {
		return x.Background
	}
	return nil
}

func (x *Theme) GetTrueColor() bool {
	if x != nil {
		return x.TrueColor
	}
	return false
}

func (x *Theme) GetSchemeKnown() bool {
	if x != nil {
		return x.SchemeKnown
	}
	return false
}

func (x *Theme) GetLight() bool {
	if x != nil {
		return x.Light
	}
	return false
}

func (x *Theme) GetPaletteKnown() uint32 {
	if x != nil {
		return x.PaletteKnown
	}
	return 0
}

func (x *Theme) GetPalette() []*RGB {
	if x != nil {
		return x.Palette
	}
	return nil
}

// ImagePush carries one Kitty graphics payload.
type ImagePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputSeq      uint64                 `protobuf:"varint,1,opt,name=input_seq,json=inputSeq,proto3" json:"input_seq,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePush) Reset() {
	*x = ImagePush{}
	mi := &file_terminal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePush) ProtoMessage() {}

func (x *ImagePush) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePush.ProtoReflect.Descriptor instead.
func (*ImagePush) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{6}
}

func (x *ImagePush) GetInputSeq() uint64 {
	if x != nil {
		return x.InputSeq
	}
	return 0
}

func (x *ImagePush) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ImagePush) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ClientNotice is a fixed one-byte client signal.
type ClientNotice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Closed action taxonomy: 1 = clipboard fallback, 2 = clipboard too
	// large, 3 = link degraded, 4 = link connected.
	Action        uint32 `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientNotice) Reset() {
	*x = ClientNotice{}
	mi := &file_terminal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientNotice) ProtoMessage() {}

func (x *ClientNotice) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientNotice.ProtoReflect.Descriptor instead.
func (*ClientNotice) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{7}
}

func (x *ClientNotice) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// OutputResetRequest restarts the output chain. Empty marker.
type OutputResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResetRequest) Reset() {
	*x = OutputResetRequest{}
	mi := &file_terminal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResetRequest) ProtoMessage() {}

func (x *OutputResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResetRequest.ProtoReflect.Descriptor instead.
func (*OutputResetRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{8}
}

// UIFence orders UI operations by action.
type UIFence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIFence) Reset() {
	*x = UIFence{}
	mi := &file_terminal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIFence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIFence) ProtoMessage() {}

func (x *UIFence) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIFence.ProtoReflect.Descriptor instead.
func (*UIFence) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{9}
}

func (x *UIFence) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

// UIReceipt reports the processed output boundary.
type UIReceipt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActionId        uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Epoch           uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	State           uint64                 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	ViewPublication uint64                 `protobuf:"varint,4,opt,name=view_publication,json=viewPublication,proto3" json:"view_publication,omitempty"`
	// Closed outcome taxonomy: 1 = processed, 2 = unavailable.
	Outcome       uint32 `protobuf:"varint,5,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIReceipt) Reset() {
	*x = UIReceipt{}
	mi := &file_terminal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIReceipt) ProtoMessage() {}

func (x *UIReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIReceipt.ProtoReflect.Descriptor instead.
func (*UIReceipt) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{10}
}

func (x *UIReceipt) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *UIReceipt) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *UIReceipt) GetState() uint64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UIReceipt) GetViewPublication() uint64 {
	if x != nil {
		return x.ViewPublication
	}
	return 0
}

func (x *UIReceipt) GetOutcome() uint32 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

// UIViewUpdate publishes a view boundary without terminal data.
type UIViewUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	State         uint64                 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Context       *ViewContext           `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIViewUpdate) Reset() {
	*x = UIViewUpdate{}
	mi := &file_terminal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIViewUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIViewUpdate) ProtoMessage() {}

func (x *UIViewUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIViewUpdate.ProtoReflect.Descriptor instead.
func (*UIViewUpdate) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{11}
}

func (x *UIViewUpdate) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *UIViewUpdate) GetState() uint64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UIViewUpdate) GetContext() *ViewContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// RemotePreviewRequest asks for a bounded remote viewport.
type RemotePreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Target        *RemoteTarget          `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePreviewRequest) Reset() {
	*x = RemotePreviewRequest{}
	mi := &file_terminal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePreviewRequest) ProtoMessage() {}

func (x *RemotePreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePreviewRequest.ProtoReflect.Descriptor instead.
func (*RemotePreviewRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{12}
}

func (x *RemotePreviewRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RemotePreviewRequest) GetTarget() *RemoteTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RemotePreviewRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RemotePreviewRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// RemotePreview is a bounded row-major styled-cell viewport.
type RemotePreview struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Closed status taxonomy: 0 = ok, 1 = unavailable, 2 = no such target,
	// 3 = stale, 4 = malformed, 5 = too large.
	Status        uint32         `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	LifecycleId   *LifecycleID   `protobuf:"bytes,3,opt,name=lifecycle_id,json=lifecycleId,proto3" json:"lifecycle_id,omitempty"`
	TabId         string         `protobuf:"bytes,4,opt,name=tab_id,json=tabId,proto3" json:"tab_id,omitempty"`
	Revision      uint64         `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Width         uint32         `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32         `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Cells         []*PreviewCell `protobuf:"bytes,8,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePreview) Reset() {
	*x = RemotePreview{}
	mi := &file_terminal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePreview) ProtoMessage() {}

func (x *RemotePreview) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePreview.ProtoReflect.Descriptor instead.
func (*RemotePreview) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{13}
}

func (x *RemotePreview) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RemotePreview) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemotePreview) GetLifecycleId() *LifecycleID {
	if x != nil {
		return x.LifecycleId
	}
	return nil
}

func (x *RemotePreview) GetTabId() string {
	if x != nil {
		return x.TabId
	}
	return ""
}

func (x *RemotePreview) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RemotePreview) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RemotePreview) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RemotePreview) GetCells() []*PreviewCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// PickerPreviewRequest asks for one picker's row viewport.
type PickerPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	InteractionId uint64                 `protobuf:"varint,2,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Width         uint32                 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickerPreviewRequest) Reset() {
	*x = PickerPreviewRequest{}
	mi := &file_terminal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickerPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickerPreviewRequest) ProtoMessage() {}

func (x *PickerPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickerPreviewRequest.ProtoReflect.Descriptor instead.
func (*PickerPreviewRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{14}
}

func (x *PickerPreviewRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PickerPreviewRequest) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *PickerPreviewRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PickerPreviewRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PickerPreviewRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PickerPreviewRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// PickerPreview is the row viewport of one picker row.
type PickerPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	InteractionId uint64                 `protobuf:"varint,2,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// Closed status taxonomy: 0 = ok, 1 = no such target, 2 = unavailable,
	// 3 = too large.
	Status        uint32         `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Width         uint32         `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32         `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Cells         []*PreviewCell `protobuf:"bytes,8,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickerPreview) Reset() {
	*x = PickerPreview{}
	mi := &file_terminal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickerPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickerPreview) ProtoMessage() {}

func (x *PickerPreview) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickerPreview.ProtoReflect.Descriptor instead.
func (*PickerPreview) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{15}
}

func (x *PickerPreview) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PickerPreview) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *PickerPreview) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PickerPreview) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PickerPreview) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PickerPreview) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PickerPreview) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PickerPreview) GetCells() []*PreviewCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_terminal_proto protoreflect.FileDescriptor

const file_terminal_proto_rawDesc = "" +
	"\n" +
	"\x0eterminal.proto\x12\vvev.wire.v1\x1a\fcommon.proto\x1a\rsession.proto\"\xa9\x01\n" +
	"\vViewContext\x12 \n" +
	"\vpublication\x18\x01 \x01(\x04R\vpublication\x129\n" +
	"\x05route\x18\x02 \x01(\v2#.vev.wire.v1.CommittedRouteIdentityR\x05route\x12\x15\n" +
	"\x06tab_id\x18\x03 \x01(\tR\x05tabId\x12&\n" +
	"\x0ffocused_pane_id\x18\x04 \x01(\tR\rfocusedPaneId\"\xd9\x02\n" +
	"\x06Output\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04base\x18\x02 \x01(\x04R\x04base\x12\x1b\n" +
	"\tnew_state\x18\x03 \x01(\x04R\bnewState\x12\x12\n" +
	"\x04echo\x18\x04 \x01(\x04R\x04echo\x12#\n" +
	"\rview_revision\x18\x05 \x01(\x04R\fviewRevision\x12\x12\n" +
	"\x04cols\x18\x06 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\a \x01(\rR\x04rows\x12\x12\n" +
	"\x04full\x18\b \x01(\bR\x04full\x122\n" +
	"\acontext\x18\t \x01(\v2\x18.vev.wire.v1.ViewContextR\acontext\x12\x1a\n" +
	"\bencoding\x18\n" +
	" \x01(\rR\bencoding\x12/\n" +
	"\x13uncompressed_length\x18\v \x01(\x04R\x12uncompressedLength\x12\x12\n" +
	"\x04data\x18\f \x01(\fR\x04data\"1\n" +
	"\x03Ack\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x04R\x05state\"U\n" +
	"\x05Input\x12\x1b\n" +
	"\tinput_seq\x18\x01 \x01(\x04R\binputSeq\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\x04R\bactionId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"t\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x1f\n" +
	"\vpixel_width\x18\x03 \x01(\rR\n" +
	"pixelWidth\x12!\n" +
	"\fpixel_height\x18\x04 \x01(\rR\vpixelHeight\"\xe2\x02\n" +
	"\x05Theme\x12%\n" +
	"\x0ehas_foreground\x18\x01 \x01(\bR\rhasForeground\x120\n" +
	"\n" +
	"foreground\x18\x02 \x01(\v2\x10.vev.wire.v1.RGBR\n" +
	"foreground\x12%\n" +
	"\x0ehas_background\x18\x03 \x01(\bR\rhasBackground\x120\n" +
	"\n" +
	"background\x18\x04 \x01(\v2\x10.vev.wire.v1.RGBR\n" +
	"background\x12\x1d\n" +
	"\n" +
	"true_color\x18\x05 \x01(\bR\ttrueColor\x12!\n" +
	"\fscheme_known\x18\x06 \x01(\bR\vschemeKnown\x12\x14\n" +
	"\x05light\x18\a \x01(\bR\x05light\x12#\n" +
	"\rpalette_known\x18\b \x01(\rR\fpaletteKnown\x12*\n" +
	"\apalette\x18\t \x03(\v2\x10.vev.wire.v1.RGBR\apalette\"P\n" +
	"\tImagePush\x12\x1b\n" +
	"\tinput_seq\x18\x01 \x01(\x04R\binputSeq\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"&\n" +
	"\fClientNotice\x12\x16\n" +
	"\x06action\x18\x01 \x01(\rR\x06action\"\x14\n" +
	"\x12OutputResetRequest\"&\n" +
	"\aUIFence\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\"\x99\x01\n" +
	"\tUIReceipt\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x04R\x05state\x12)\n" +
	"\x10view_publication\x18\x04 \x01(\x04R\x0fviewPublication\x12\x18\n" +
	"\aoutcome\x18\x05 \x01(\rR\aoutcome\"n\n" +
	"\fUIViewUpdate\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x04R\x05state\x122\n" +
	"\acontext\x18\x03 \x01(\v2\x18.vev.wire.v1.ViewContextR\acontext\"\x91\x01\n" +
	"\x14RemotePreviewRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x121\n" +
	"\x06target\x18\x02 \x01(\v2\x19.vev.wire.v1.RemoteTargetR\x06target\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\"\x8f\x02\n" +
	"\rRemotePreview\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12;\n" +
	"\flifecycle_id\x18\x03 \x01(\v2\x18.vev.wire.v1.LifecycleIDR\vlifecycleId\x12\x15\n" +
	"\x06tab_id\x18\x04 \x01(\tR\x05tabId\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\x12\x14\n" +
	"\x05width\x18\x06 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\rR\x06height\x12.\n" +
	"\x05cells\x18\b \x03(\v2\x18.vev.wire.v1.PreviewCellR\x05cells\"\xb4\x01\n" +
	"\x14PickerPreviewRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12%\n" +
	"\x0einteraction_id\x18\x02 \x01(\x04R\rinteractionId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05width\x18\x05 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\rR\x06height\"\xf5\x01\n" +
	"\rPickerPreview\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12%\n" +
	"\x0einteraction_id\x18\x02 \x01(\x04R\rinteractionId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\x12\x14\n" +
	"\x05width\x18\x06 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\rR\x06height\x12.\n" +
	"\x05cells\x18\b \x03(\v2\x18.vev.wire.v1.PreviewCellR\x05cellsB-Z+github.com/bnema/vev/internal/protocol/wireb\x06proto3"

var (
	file_terminal_proto_rawDescOnce sync.Once
	file_terminal_proto_rawDescData []byte
)

func file_terminal_proto_rawDescGZIP() []byte {
	file_terminal_proto_rawDescOnce.Do(func() {
		file_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terminal_proto_rawDesc), len(file_terminal_proto_rawDesc)))
	})
	return file_terminal_proto_rawDescData
}

var file_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_terminal_proto_goTypes = []any{
	(*ViewContext)(nil),            // 0: vev.wire.v1.ViewContext
	(*Output)(nil),                 // 1: vev.wire.v1.Output
	(*Ack)(nil),                    // 2: vev.wire.v1.Ack
	(*Input)(nil),                  // 3: vev.wire.v1.Input
	(*Resize)(nil),                 // 4: vev.wire.v1.Resize
	(*Theme)(nil),                  // 5: vev.wire.v1.Theme
	(*ImagePush)(nil),              // 6: vev.wire.v1.ImagePush
	(*ClientNotice)(nil),           // 7: vev.wire.v1.ClientNotice
	(*OutputResetRequest)(nil),     // 8: vev.wire.v1.OutputResetRequest
	(*UIFence)(nil),                // 9: vev.wire.v1.UIFence
	(*UIReceipt)(nil),              // 10: vev.wire.v1.UIReceipt
	(*UIViewUpdate)(nil),           // 11: vev.wire.v1.UIViewUpdate
	(*RemotePreviewRequest)(nil),   // 12: vev.wire.v1.RemotePreviewRequest
	(*RemotePreview)(nil),          // 13: vev.wire.v1.RemotePreview
	(*PickerPreviewRequest)(nil),   // 14: vev.wire.v1.PickerPreviewRequest
	(*PickerPreview)(nil),          // 15: vev.wire.v1.PickerPreview
	(*CommittedRouteIdentity)(nil), // 16: vev.wire.v1.CommittedRouteIdentity
	(*RGB)(nil),                    // 17: vev.wire.v1.RGB
	(*RemoteTarget)(nil),           // 18: vev.wire.v1.RemoteTarget
	(*LifecycleID)(nil),            // 19: vev.wire.v1.LifecycleID
	(*PreviewCell)(nil),            // 20: vev.wire.v1.PreviewCell
}
var file_terminal_proto_depIdxs = []int32{
	16, // 0: vev.wire.v1.ViewContext.route:type_name -> vev.wire.v1.CommittedRouteIdentity
	0,  // 1: vev.wire.v1.Output.context:type_name -> vev.wire.v1.ViewContext
	17, // 2: vev.wire.v1.Theme.foreground:type_name -> vev.wire.v1.RGB
	17, // 3: vev.wire.v1.Theme.background:type_name -> vev.wire.v1.RGB
	17, // 4: vev.wire.v1.Theme.palette:type_name -> vev.wire.v1.RGB
	0,  // 5: vev.wire.v1.UIViewUpdate.context:type_name -> vev.wire.v1.ViewContext
	18, // 6: vev.wire.v1.RemotePreviewRequest.target:type_name -> vev.wire.v1.RemoteTarget
	19, // 7: vev.wire.v1.RemotePreview.lifecycle_id:type_name -> vev.wire.v1.LifecycleID
	20, // 8: vev.wire.v1.RemotePreview.cells:type_name -> vev.wire.v1.PreviewCell
	20, // 9: vev.wire.v1.PickerPreview.cells:type_name -> vev.wire.v1.PreviewCell
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_terminal_proto_init() }
func file_terminal_proto_init() {
	if File_terminal_proto != nil {
		return
	}
	file_common_proto_init()
	file_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terminal_proto_rawDesc), len(file_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_terminal_proto_goTypes,
		DependencyIndexes: file_terminal_proto_depIdxs,
		MessageInfos:      file_terminal_proto_msgTypes,
	}.Build()
	File_terminal_proto = out.File
	file_terminal_proto_goTypes = nil
	file_terminal_proto_depIdxs = nil
}
