// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/bnema/vev/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrokerRouteAuthority creates a new instance of MockBrokerRouteAuthority. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerRouteAuthority(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerRouteAuthority {
	mock := &MockBrokerRouteAuthority{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerRouteAuthority is an autogenerated mock type for the BrokerRouteAuthority type
type MockBrokerRouteAuthority struct {
	mock.Mock
}

type MockBrokerRouteAuthority_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerRouteAuthority) EXPECT() *MockBrokerRouteAuthority_Expecter {
	return &MockBrokerRouteAuthority_Expecter{mock: &_m.Mock}
}

// ResolveDialTarget provides a mock function for the type MockBrokerRouteAuthority
func (_mock *MockBrokerRouteAuthority) ResolveDialTarget(context1 context.Context, brokerOpenStreamRequest ports.BrokerOpenStreamRequest) (ports.BrokerDialTarget, error) {
	ret := _mock.Called(context1, brokerOpenStreamRequest)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDialTarget")
	}

	var r0 ports.BrokerDialTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerOpenStreamRequest) (ports.BrokerDialTarget, error)); ok {
		return returnFunc(context1, brokerOpenStreamRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerOpenStreamRequest) ports.BrokerDialTarget); ok {
		r0 = returnFunc(context1, brokerOpenStreamRequest)
	} else {
		r0 = ret.Get(0).(ports.BrokerDialTarget)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.BrokerOpenStreamRequest) error); ok {
		r1 = returnFunc(context1, brokerOpenStreamRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerRouteAuthority_ResolveDialTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDialTarget'
type MockBrokerRouteAuthority_ResolveDialTarget_Call struct {
	*mock.Call
}

// ResolveDialTarget is a helper method to define mock.On call
//   - context1 context.Context
//   - brokerOpenStreamRequest ports.BrokerOpenStreamRequest
func (_e *MockBrokerRouteAuthority_Expecter) ResolveDialTarget(context1 any, brokerOpenStreamRequest any) *MockBrokerRouteAuthority_ResolveDialTarget_Call {
	return &MockBrokerRouteAuthority_ResolveDialTarget_Call{Call: _e.mock.On("ResolveDialTarget", context1, brokerOpenStreamRequest)}
}

func (_c *MockBrokerRouteAuthority_ResolveDialTarget_Call) Run(run func(context1 context.Context, brokerOpenStreamRequest ports.BrokerOpenStreamRequest)) *MockBrokerRouteAuthority_ResolveDialTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.BrokerOpenStreamRequest
		if args[1] != nil {
			arg1 = args[1].(ports.BrokerOpenStreamRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerRouteAuthority_ResolveDialTarget_Call) Return(brokerDialTarget ports.BrokerDialTarget, err error) *MockBrokerRouteAuthority_ResolveDialTarget_Call {
	_c.Call.Return(brokerDialTarget, err)
	return _c
}

func (_c *MockBrokerRouteAuthority_ResolveDialTarget_Call) RunAndReturn(run func(context1 context.Context, brokerOpenStreamRequest ports.BrokerOpenStreamRequest) (ports.BrokerDialTarget, error)) *MockBrokerRouteAuthority_ResolveDialTarget_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerIdentityBinder creates a new instance of MockBrokerIdentityBinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerIdentityBinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerIdentityBinder {
	mock := &MockBrokerIdentityBinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerIdentityBinder is an autogenerated mock type for the BrokerIdentityBinder type
type MockBrokerIdentityBinder struct {
	mock.Mock
}

type MockBrokerIdentityBinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerIdentityBinder) EXPECT() *MockBrokerIdentityBinder_Expecter {
	return &MockBrokerIdentityBinder_Expecter{mock: &_m.Mock}
}

// BindAuthenticatedIdentity provides a mock function for the type MockBrokerIdentityBinder
func (_mock *MockBrokerIdentityBinder) BindAuthenticatedIdentity(context1 context.Context, brokerIdentityBindingRequest ports.BrokerIdentityBindingRequest) (ports.BrokerDaemonIdentity, error) {
	ret := _mock.Called(context1, brokerIdentityBindingRequest)

	if len(ret) == 0 {
		panic("no return value specified for BindAuthenticatedIdentity")
	}

	var r0 ports.BrokerDaemonIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerIdentityBindingRequest) (ports.BrokerDaemonIdentity, error)); ok {
		return returnFunc(context1, brokerIdentityBindingRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerIdentityBindingRequest) ports.BrokerDaemonIdentity); ok {
		r0 = returnFunc(context1, brokerIdentityBindingRequest)
	} else {
		r0 = ret.Get(0).(ports.BrokerDaemonIdentity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.BrokerIdentityBindingRequest) error); ok {
		r1 = returnFunc(context1, brokerIdentityBindingRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindAuthenticatedIdentity'
type MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call struct {
	*mock.Call
}

// BindAuthenticatedIdentity is a helper method to define mock.On call
//   - context1 context.Context
//   - brokerIdentityBindingRequest ports.BrokerIdentityBindingRequest
func (_e *MockBrokerIdentityBinder_Expecter) BindAuthenticatedIdentity(context1 any, brokerIdentityBindingRequest any) *MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call {
	return &MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call{Call: _e.mock.On("BindAuthenticatedIdentity", context1, brokerIdentityBindingRequest)}
}

func (_c *MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call) Run(run func(context1 context.Context, brokerIdentityBindingRequest ports.BrokerIdentityBindingRequest)) *MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.BrokerIdentityBindingRequest
		if args[1] != nil {
			arg1 = args[1].(ports.BrokerIdentityBindingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call) Return(brokerDaemonIdentity ports.BrokerDaemonIdentity, err error) *MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call {
	_c.Call.Return(brokerDaemonIdentity, err)
	return _c
}

func (_c *MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call) RunAndReturn(run func(context1 context.Context, brokerIdentityBindingRequest ports.BrokerIdentityBindingRequest) (ports.BrokerDaemonIdentity, error)) *MockBrokerIdentityBinder_BindAuthenticatedIdentity_Call {
	_c.Call.Return(run)
	return _c
}
