// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/bnema/vev/internal/domain"
	"github.com/bnema/vev/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrokerSubscription creates a new instance of MockBrokerSubscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerSubscription {
	mock := &MockBrokerSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerSubscription is an autogenerated mock type for the BrokerSubscription type
type MockBrokerSubscription struct {
	mock.Mock
}

type MockBrokerSubscription_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerSubscription) EXPECT() *MockBrokerSubscription_Expecter {
	return &MockBrokerSubscription_Expecter{mock: &_m.Mock}
}

// Changed provides a mock function for the type MockBrokerSubscription
func (_mock *MockBrokerSubscription) Changed() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Changed")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockBrokerSubscription_Changed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Changed'
type MockBrokerSubscription_Changed_Call struct {
	*mock.Call
}

// Changed is a helper method to define mock.On call
func (_e *MockBrokerSubscription_Expecter) Changed() *MockBrokerSubscription_Changed_Call {
	return &MockBrokerSubscription_Changed_Call{Call: _e.mock.On("Changed")}
}

func (_c *MockBrokerSubscription_Changed_Call) Run(run func()) *MockBrokerSubscription_Changed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerSubscription_Changed_Call) Return(valCh <-chan struct{}) *MockBrokerSubscription_Changed_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockBrokerSubscription_Changed_Call) RunAndReturn(run func() <-chan struct{}) *MockBrokerSubscription_Changed_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBrokerSubscription
func (_mock *MockBrokerSubscription) Close() {
	_mock.Called()
	return
}

// MockBrokerSubscription_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBrokerSubscription_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBrokerSubscription_Expecter) Close() *MockBrokerSubscription_Close_Call {
	return &MockBrokerSubscription_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBrokerSubscription_Close_Call) Run(run func()) *MockBrokerSubscription_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerSubscription_Close_Call) Return() *MockBrokerSubscription_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBrokerSubscription_Close_Call) RunAndReturn(run func()) *MockBrokerSubscription_Close_Call {
	_c.Run(run)
	return _c
}

// NewMockBrokerService creates a new instance of MockBrokerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerService {
	mock := &MockBrokerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerService is an autogenerated mock type for the BrokerService type
type MockBrokerService struct {
	mock.Mock
}

type MockBrokerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerService) EXPECT() *MockBrokerService_Expecter {
	return &MockBrokerService_Expecter{mock: &_m.Mock}
}

// AddHost provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) AddHost(ctx context.Context, target string) error {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for AddHost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerService_AddHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHost'
type MockBrokerService_AddHost_Call struct {
	*mock.Call
}

// AddHost is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockBrokerService_Expecter) AddHost(ctx any, target any) *MockBrokerService_AddHost_Call {
	return &MockBrokerService_AddHost_Call{Call: _e.mock.On("AddHost", ctx, target)}
}

func (_c *MockBrokerService_AddHost_Call) Run(run func(ctx context.Context, target string)) *MockBrokerService_AddHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerService_AddHost_Call) Return(err error) *MockBrokerService_AddHost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerService_AddHost_Call) RunAndReturn(run func(ctx context.Context, target string) error) *MockBrokerService_AddHost_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBrokerService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBrokerService_Expecter) Close() *MockBrokerService_Close_Call {
	return &MockBrokerService_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBrokerService_Close_Call) Run(run func()) *MockBrokerService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerService_Close_Call) Return(err error) *MockBrokerService_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerService_Close_Call) RunAndReturn(run func() error) *MockBrokerService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CloseStream provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) CloseStream(connection ports.BrokerConnectionID, stream ports.BrokerStreamID) error {
	ret := _mock.Called(connection, stream)

	if len(ret) == 0 {
		panic("no return value specified for CloseStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ports.BrokerConnectionID, ports.BrokerStreamID) error); ok {
		r0 = returnFunc(connection, stream)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerService_CloseStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseStream'
type MockBrokerService_CloseStream_Call struct {
	*mock.Call
}

// CloseStream is a helper method to define mock.On call
//   - connection ports.BrokerConnectionID
//   - stream ports.BrokerStreamID
func (_e *MockBrokerService_Expecter) CloseStream(connection any, stream any) *MockBrokerService_CloseStream_Call {
	return &MockBrokerService_CloseStream_Call{Call: _e.mock.On("CloseStream", connection, stream)}
}

func (_c *MockBrokerService_CloseStream_Call) Run(run func(connection ports.BrokerConnectionID, stream ports.BrokerStreamID)) *MockBrokerService_CloseStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.BrokerConnectionID
		if args[0] != nil {
			arg0 = args[0].(ports.BrokerConnectionID)
		}
		var arg1 ports.BrokerStreamID
		if args[1] != nil {
			arg1 = args[1].(ports.BrokerStreamID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerService_CloseStream_Call) Return(err error) *MockBrokerService_CloseStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerService_CloseStream_Call) RunAndReturn(run func(connection ports.BrokerConnectionID, stream ports.BrokerStreamID) error) *MockBrokerService_CloseStream_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectionID provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) ConnectionID() ports.BrokerConnectionID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectionID")
	}

	var r0 ports.BrokerConnectionID
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerConnectionID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerConnectionID)
		}
	}
	return r0
}

// MockBrokerService_ConnectionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionID'
type MockBrokerService_ConnectionID_Call struct {
	*mock.Call
}

// ConnectionID is a helper method to define mock.On call
func (_e *MockBrokerService_Expecter) ConnectionID() *MockBrokerService_ConnectionID_Call {
	return &MockBrokerService_ConnectionID_Call{Call: _e.mock.On("ConnectionID")}
}

func (_c *MockBrokerService_ConnectionID_Call) Run(run func()) *MockBrokerService_ConnectionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerService_ConnectionID_Call) Return(brokerConnectionID ports.BrokerConnectionID) *MockBrokerService_ConnectionID_Call {
	_c.Call.Return(brokerConnectionID)
	return _c
}

func (_c *MockBrokerService_ConnectionID_Call) RunAndReturn(run func() ports.BrokerConnectionID) *MockBrokerService_ConnectionID_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockBrokerService_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockBrokerService_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockBrokerService_Expecter) Done() *MockBrokerService_Done_Call {
	return &MockBrokerService_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockBrokerService_Done_Call) Run(run func()) *MockBrokerService_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerService_Done_Call) Return(valCh <-chan struct{}) *MockBrokerService_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockBrokerService_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockBrokerService_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerService_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockBrokerService_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockBrokerService_Expecter) Err() *MockBrokerService_Err_Call {
	return &MockBrokerService_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockBrokerService_Err_Call) Run(run func()) *MockBrokerService_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerService_Err_Call) Return(err error) *MockBrokerService_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerService_Err_Call) RunAndReturn(run func() error) *MockBrokerService_Err_Call {
	_c.Call.Return(run)
	return _c
}

// OpenStream provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) OpenStream(ctx context.Context, request ports.BrokerOpenStreamRequest) (ports.BrokerLogicalConnection, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for OpenStream")
	}

	var r0 ports.BrokerLogicalConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerOpenStreamRequest) (ports.BrokerLogicalConnection, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerOpenStreamRequest) ports.BrokerLogicalConnection); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerLogicalConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.BrokerOpenStreamRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerService_OpenStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenStream'
type MockBrokerService_OpenStream_Call struct {
	*mock.Call
}

// OpenStream is a helper method to define mock.On call
//   - ctx context.Context
//   - request ports.BrokerOpenStreamRequest
func (_e *MockBrokerService_Expecter) OpenStream(ctx any, request any) *MockBrokerService_OpenStream_Call {
	return &MockBrokerService_OpenStream_Call{Call: _e.mock.On("OpenStream", ctx, request)}
}

func (_c *MockBrokerService_OpenStream_Call) Run(run func(ctx context.Context, request ports.BrokerOpenStreamRequest)) *MockBrokerService_OpenStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.BrokerOpenStreamRequest
		if args[1] != nil {
			arg1 = args[1].(ports.BrokerOpenStreamRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerService_OpenStream_Call) Return(brokerLogicalConnection ports.BrokerLogicalConnection, err error) *MockBrokerService_OpenStream_Call {
	_c.Call.Return(brokerLogicalConnection, err)
	return _c
}

func (_c *MockBrokerService_OpenStream_Call) RunAndReturn(run func(ctx context.Context, request ports.BrokerOpenStreamRequest) (ports.BrokerLogicalConnection, error)) *MockBrokerService_OpenStream_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveHost provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) RemoveHost(ctx context.Context, target string) (bool, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for RemoveHost")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerService_RemoveHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHost'
type MockBrokerService_RemoveHost_Call struct {
	*mock.Call
}

// RemoveHost is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockBrokerService_Expecter) RemoveHost(ctx any, target any) *MockBrokerService_RemoveHost_Call {
	return &MockBrokerService_RemoveHost_Call{Call: _e.mock.On("RemoveHost", ctx, target)}
}

func (_c *MockBrokerService_RemoveHost_Call) Run(run func(ctx context.Context, target string)) *MockBrokerService_RemoveHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerService_RemoveHost_Call) Return(b bool, err error) *MockBrokerService_RemoveHost_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBrokerService_RemoveHost_Call) RunAndReturn(run func(ctx context.Context, target string) (bool, error)) *MockBrokerService_RemoveHost_Call {
	_c.Call.Return(run)
	return _c
}

// RequestReconcile provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) RequestReconcile(endpoint string) {
	_mock.Called(endpoint)
	return
}

// MockBrokerService_RequestReconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestReconcile'
type MockBrokerService_RequestReconcile_Call struct {
	*mock.Call
}

// RequestReconcile is a helper method to define mock.On call
//   - endpoint string
func (_e *MockBrokerService_Expecter) RequestReconcile(endpoint any) *MockBrokerService_RequestReconcile_Call {
	return &MockBrokerService_RequestReconcile_Call{Call: _e.mock.On("RequestReconcile", endpoint)}
}

func (_c *MockBrokerService_RequestReconcile_Call) Run(run func(endpoint string)) *MockBrokerService_RequestReconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBrokerService_RequestReconcile_Call) Return() *MockBrokerService_RequestReconcile_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBrokerService_RequestReconcile_Call) RunAndReturn(run func(endpoint string)) *MockBrokerService_RequestReconcile_Call {
	_c.Run(run)
	return _c
}

// Snapshot provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) Snapshot() ports.BrokerSnapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 ports.BrokerSnapshot
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerSnapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.BrokerSnapshot)
	}
	return r0
}

// MockBrokerService_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockBrokerService_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockBrokerService_Expecter) Snapshot() *MockBrokerService_Snapshot_Call {
	return &MockBrokerService_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockBrokerService_Snapshot_Call) Run(run func()) *MockBrokerService_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerService_Snapshot_Call) Return(brokerSnapshot ports.BrokerSnapshot) *MockBrokerService_Snapshot_Call {
	_c.Call.Return(brokerSnapshot)
	return _c
}

func (_c *MockBrokerService_Snapshot_Call) RunAndReturn(run func() ports.BrokerSnapshot) *MockBrokerService_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockBrokerService
func (_mock *MockBrokerService) Subscribe() (ports.BrokerSubscription, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 ports.BrokerSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (ports.BrokerSubscription, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerSubscription); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerService_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBrokerService_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
func (_e *MockBrokerService_Expecter) Subscribe() *MockBrokerService_Subscribe_Call {
	return &MockBrokerService_Subscribe_Call{Call: _e.mock.On("Subscribe")}
}

func (_c *MockBrokerService_Subscribe_Call) Run(run func()) *MockBrokerService_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerService_Subscribe_Call) Return(brokerSubscription ports.BrokerSubscription, err error) *MockBrokerService_Subscribe_Call {
	_c.Call.Return(brokerSubscription, err)
	return _c
}

func (_c *MockBrokerService_Subscribe_Call) RunAndReturn(run func() (ports.BrokerSubscription, error)) *MockBrokerService_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerSnapshotStore creates a new instance of MockBrokerSnapshotStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerSnapshotStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerSnapshotStore {
	mock := &MockBrokerSnapshotStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerSnapshotStore is an autogenerated mock type for the BrokerSnapshotStore type
type MockBrokerSnapshotStore struct {
	mock.Mock
}

type MockBrokerSnapshotStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerSnapshotStore) EXPECT() *MockBrokerSnapshotStore_Expecter {
	return &MockBrokerSnapshotStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockBrokerSnapshotStore
func (_mock *MockBrokerSnapshotStore) Load() (ports.BrokerSnapshot, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 ports.BrokerSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (ports.BrokerSnapshot, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerSnapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.BrokerSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerSnapshotStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockBrokerSnapshotStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockBrokerSnapshotStore_Expecter) Load() *MockBrokerSnapshotStore_Load_Call {
	return &MockBrokerSnapshotStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockBrokerSnapshotStore_Load_Call) Run(run func()) *MockBrokerSnapshotStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerSnapshotStore_Load_Call) Return(brokerSnapshot ports.BrokerSnapshot, err error) *MockBrokerSnapshotStore_Load_Call {
	_c.Call.Return(brokerSnapshot, err)
	return _c
}

func (_c *MockBrokerSnapshotStore_Load_Call) RunAndReturn(run func() (ports.BrokerSnapshot, error)) *MockBrokerSnapshotStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockBrokerSnapshotStore
func (_mock *MockBrokerSnapshotStore) Store(brokerSnapshot ports.BrokerSnapshot) error {
	ret := _mock.Called(brokerSnapshot)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ports.BrokerSnapshot) error); ok {
		r0 = returnFunc(brokerSnapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerSnapshotStore_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockBrokerSnapshotStore_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - brokerSnapshot ports.BrokerSnapshot
func (_e *MockBrokerSnapshotStore_Expecter) Store(brokerSnapshot any) *MockBrokerSnapshotStore_Store_Call {
	return &MockBrokerSnapshotStore_Store_Call{Call: _e.mock.On("Store", brokerSnapshot)}
}

func (_c *MockBrokerSnapshotStore_Store_Call) Run(run func(brokerSnapshot ports.BrokerSnapshot)) *MockBrokerSnapshotStore_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.BrokerSnapshot
		if args[0] != nil {
			arg0 = args[0].(ports.BrokerSnapshot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBrokerSnapshotStore_Store_Call) Return(err error) *MockBrokerSnapshotStore_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerSnapshotStore_Store_Call) RunAndReturn(run func(brokerSnapshot ports.BrokerSnapshot) error) *MockBrokerSnapshotStore_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerHostProbe creates a new instance of MockBrokerHostProbe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerHostProbe(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerHostProbe {
	mock := &MockBrokerHostProbe{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerHostProbe is an autogenerated mock type for the BrokerHostProbe type
type MockBrokerHostProbe struct {
	mock.Mock
}

type MockBrokerHostProbe_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerHostProbe) EXPECT() *MockBrokerHostProbe_Expecter {
	return &MockBrokerHostProbe_Expecter{mock: &_m.Mock}
}

// Probe provides a mock function for the type MockBrokerHostProbe
func (_mock *MockBrokerHostProbe) Probe(ctx context.Context, registration domain.RemoteRegistration) (ports.RemoteHostSnapshot, error) {
	ret := _mock.Called(ctx, registration)

	if len(ret) == 0 {
		panic("no return value specified for Probe")
	}

	var r0 ports.RemoteHostSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RemoteRegistration) (ports.RemoteHostSnapshot, error)); ok {
		return returnFunc(ctx, registration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RemoteRegistration) ports.RemoteHostSnapshot); ok {
		r0 = returnFunc(ctx, registration)
	} else {
		r0 = ret.Get(0).(ports.RemoteHostSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RemoteRegistration) error); ok {
		r1 = returnFunc(ctx, registration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerHostProbe_Probe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Probe'
type MockBrokerHostProbe_Probe_Call struct {
	*mock.Call
}

// Probe is a helper method to define mock.On call
//   - ctx context.Context
//   - registration domain.RemoteRegistration
func (_e *MockBrokerHostProbe_Expecter) Probe(ctx any, registration any) *MockBrokerHostProbe_Probe_Call {
	return &MockBrokerHostProbe_Probe_Call{Call: _e.mock.On("Probe", ctx, registration)}
}

func (_c *MockBrokerHostProbe_Probe_Call) Run(run func(ctx context.Context, registration domain.RemoteRegistration)) *MockBrokerHostProbe_Probe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RemoteRegistration
		if args[1] != nil {
			arg1 = args[1].(domain.RemoteRegistration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerHostProbe_Probe_Call) Return(remoteHostSnapshot ports.RemoteHostSnapshot, err error) *MockBrokerHostProbe_Probe_Call {
	_c.Call.Return(remoteHostSnapshot, err)
	return _c
}

func (_c *MockBrokerHostProbe_Probe_Call) RunAndReturn(run func(ctx context.Context, registration domain.RemoteRegistration) (ports.RemoteHostSnapshot, error)) *MockBrokerHostProbe_Probe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerPhysicalConnection creates a new instance of MockBrokerPhysicalConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerPhysicalConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerPhysicalConnection {
	mock := &MockBrokerPhysicalConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerPhysicalConnection is an autogenerated mock type for the BrokerPhysicalConnection type
type MockBrokerPhysicalConnection struct {
	mock.Mock
}

type MockBrokerPhysicalConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerPhysicalConnection) EXPECT() *MockBrokerPhysicalConnection_Expecter {
	return &MockBrokerPhysicalConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerPhysicalConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBrokerPhysicalConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBrokerPhysicalConnection_Expecter) Close() *MockBrokerPhysicalConnection_Close_Call {
	return &MockBrokerPhysicalConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBrokerPhysicalConnection_Close_Call) Run(run func()) *MockBrokerPhysicalConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_Close_Call) Return(err error) *MockBrokerPhysicalConnection_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerPhysicalConnection_Close_Call) RunAndReturn(run func() error) *MockBrokerPhysicalConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockBrokerPhysicalConnection_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockBrokerPhysicalConnection_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockBrokerPhysicalConnection_Expecter) Done() *MockBrokerPhysicalConnection_Done_Call {
	return &MockBrokerPhysicalConnection_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockBrokerPhysicalConnection_Done_Call) Run(run func()) *MockBrokerPhysicalConnection_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_Done_Call) Return(valCh <-chan struct{}) *MockBrokerPhysicalConnection_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockBrokerPhysicalConnection_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockBrokerPhysicalConnection_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerPhysicalConnection_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockBrokerPhysicalConnection_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockBrokerPhysicalConnection_Expecter) Err() *MockBrokerPhysicalConnection_Err_Call {
	return &MockBrokerPhysicalConnection_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockBrokerPhysicalConnection_Err_Call) Run(run func()) *MockBrokerPhysicalConnection_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_Err_Call) Return(err error) *MockBrokerPhysicalConnection_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerPhysicalConnection_Err_Call) RunAndReturn(run func() error) *MockBrokerPhysicalConnection_Err_Call {
	_c.Call.Return(run)
	return _c
}

// FailureKind provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) FailureKind() domain.RemoteFailureKind {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FailureKind")
	}

	var r0 domain.RemoteFailureKind
	if returnFunc, ok := ret.Get(0).(func() domain.RemoteFailureKind); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.RemoteFailureKind)
	}
	return r0
}

// MockBrokerPhysicalConnection_FailureKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailureKind'
type MockBrokerPhysicalConnection_FailureKind_Call struct {
	*mock.Call
}

// FailureKind is a helper method to define mock.On call
func (_e *MockBrokerPhysicalConnection_Expecter) FailureKind() *MockBrokerPhysicalConnection_FailureKind_Call {
	return &MockBrokerPhysicalConnection_FailureKind_Call{Call: _e.mock.On("FailureKind")}
}

func (_c *MockBrokerPhysicalConnection_FailureKind_Call) Run(run func()) *MockBrokerPhysicalConnection_FailureKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_FailureKind_Call) Return(remoteFailureKind domain.RemoteFailureKind) *MockBrokerPhysicalConnection_FailureKind_Call {
	_c.Call.Return(remoteFailureKind)
	return _c
}

func (_c *MockBrokerPhysicalConnection_FailureKind_Call) RunAndReturn(run func() domain.RemoteFailureKind) *MockBrokerPhysicalConnection_FailureKind_Call {
	_c.Call.Return(run)
	return _c
}

// Identity provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) Identity() ports.BrokerDaemonIdentity {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Identity")
	}

	var r0 ports.BrokerDaemonIdentity
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerDaemonIdentity); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.BrokerDaemonIdentity)
	}
	return r0
}

// MockBrokerPhysicalConnection_Identity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identity'
type MockBrokerPhysicalConnection_Identity_Call struct {
	*mock.Call
}

// Identity is a helper method to define mock.On call
func (_e *MockBrokerPhysicalConnection_Expecter) Identity() *MockBrokerPhysicalConnection_Identity_Call {
	return &MockBrokerPhysicalConnection_Identity_Call{Call: _e.mock.On("Identity")}
}

func (_c *MockBrokerPhysicalConnection_Identity_Call) Run(run func()) *MockBrokerPhysicalConnection_Identity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_Identity_Call) Return(brokerDaemonIdentity ports.BrokerDaemonIdentity) *MockBrokerPhysicalConnection_Identity_Call {
	_c.Call.Return(brokerDaemonIdentity)
	return _c
}

func (_c *MockBrokerPhysicalConnection_Identity_Call) RunAndReturn(run func() ports.BrokerDaemonIdentity) *MockBrokerPhysicalConnection_Identity_Call {
	_c.Call.Return(run)
	return _c
}

// Incarnation provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) Incarnation() ports.BrokerDaemonIncarnation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Incarnation")
	}

	var r0 ports.BrokerDaemonIncarnation
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerDaemonIncarnation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerDaemonIncarnation)
		}
	}
	return r0
}

// MockBrokerPhysicalConnection_Incarnation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incarnation'
type MockBrokerPhysicalConnection_Incarnation_Call struct {
	*mock.Call
}

// Incarnation is a helper method to define mock.On call
func (_e *MockBrokerPhysicalConnection_Expecter) Incarnation() *MockBrokerPhysicalConnection_Incarnation_Call {
	return &MockBrokerPhysicalConnection_Incarnation_Call{Call: _e.mock.On("Incarnation")}
}

func (_c *MockBrokerPhysicalConnection_Incarnation_Call) Run(run func()) *MockBrokerPhysicalConnection_Incarnation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_Incarnation_Call) Return(brokerDaemonIncarnation ports.BrokerDaemonIncarnation) *MockBrokerPhysicalConnection_Incarnation_Call {
	_c.Call.Return(brokerDaemonIncarnation)
	return _c
}

func (_c *MockBrokerPhysicalConnection_Incarnation_Call) RunAndReturn(run func() ports.BrokerDaemonIncarnation) *MockBrokerPhysicalConnection_Incarnation_Call {
	_c.Call.Return(run)
	return _c
}

// OpenStream provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) OpenStream(ctx context.Context, request ports.BrokerOpenStreamRequest) (ports.BrokerLogicalConnection, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for OpenStream")
	}

	var r0 ports.BrokerLogicalConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerOpenStreamRequest) (ports.BrokerLogicalConnection, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerOpenStreamRequest) ports.BrokerLogicalConnection); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerLogicalConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.BrokerOpenStreamRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerPhysicalConnection_OpenStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenStream'
type MockBrokerPhysicalConnection_OpenStream_Call struct {
	*mock.Call
}

// OpenStream is a helper method to define mock.On call
//   - ctx context.Context
//   - request ports.BrokerOpenStreamRequest
func (_e *MockBrokerPhysicalConnection_Expecter) OpenStream(ctx any, request any) *MockBrokerPhysicalConnection_OpenStream_Call {
	return &MockBrokerPhysicalConnection_OpenStream_Call{Call: _e.mock.On("OpenStream", ctx, request)}
}

func (_c *MockBrokerPhysicalConnection_OpenStream_Call) Run(run func(ctx context.Context, request ports.BrokerOpenStreamRequest)) *MockBrokerPhysicalConnection_OpenStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.BrokerOpenStreamRequest
		if args[1] != nil {
			arg1 = args[1].(ports.BrokerOpenStreamRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_OpenStream_Call) Return(brokerLogicalConnection ports.BrokerLogicalConnection, err error) *MockBrokerPhysicalConnection_OpenStream_Call {
	_c.Call.Return(brokerLogicalConnection, err)
	return _c
}

func (_c *MockBrokerPhysicalConnection_OpenStream_Call) RunAndReturn(run func(ctx context.Context, request ports.BrokerOpenStreamRequest) (ports.BrokerLogicalConnection, error)) *MockBrokerPhysicalConnection_OpenStream_Call {
	_c.Call.Return(run)
	return _c
}

// Policy provides a mock function for the type MockBrokerPhysicalConnection
func (_mock *MockBrokerPhysicalConnection) Policy() ports.BrokerPolicy {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Policy")
	}

	var r0 ports.BrokerPolicy
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerPolicy); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.BrokerPolicy)
	}
	return r0
}

// MockBrokerPhysicalConnection_Policy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Policy'
type MockBrokerPhysicalConnection_Policy_Call struct {
	*mock.Call
}

// Policy is a helper method to define mock.On call
func (_e *MockBrokerPhysicalConnection_Expecter) Policy() *MockBrokerPhysicalConnection_Policy_Call {
	return &MockBrokerPhysicalConnection_Policy_Call{Call: _e.mock.On("Policy")}
}

func (_c *MockBrokerPhysicalConnection_Policy_Call) Run(run func()) *MockBrokerPhysicalConnection_Policy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerPhysicalConnection_Policy_Call) Return(brokerPolicy ports.BrokerPolicy) *MockBrokerPhysicalConnection_Policy_Call {
	_c.Call.Return(brokerPolicy)
	return _c
}

func (_c *MockBrokerPhysicalConnection_Policy_Call) RunAndReturn(run func() ports.BrokerPolicy) *MockBrokerPhysicalConnection_Policy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerEndpointConnector creates a new instance of MockBrokerEndpointConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerEndpointConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerEndpointConnector {
	mock := &MockBrokerEndpointConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerEndpointConnector is an autogenerated mock type for the BrokerEndpointConnector type
type MockBrokerEndpointConnector struct {
	mock.Mock
}

type MockBrokerEndpointConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerEndpointConnector) EXPECT() *MockBrokerEndpointConnector_Expecter {
	return &MockBrokerEndpointConnector_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockBrokerEndpointConnector
func (_mock *MockBrokerEndpointConnector) Connect(ctx context.Context, endpoint ports.BrokerResolvedEndpoint) (ports.BrokerPhysicalConnection, error) {
	ret := _mock.Called(ctx, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 ports.BrokerPhysicalConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerResolvedEndpoint) (ports.BrokerPhysicalConnection, error)); ok {
		return returnFunc(ctx, endpoint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.BrokerResolvedEndpoint) ports.BrokerPhysicalConnection); ok {
		r0 = returnFunc(ctx, endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerPhysicalConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.BrokerResolvedEndpoint) error); ok {
		r1 = returnFunc(ctx, endpoint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerEndpointConnector_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockBrokerEndpointConnector_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoint ports.BrokerResolvedEndpoint
func (_e *MockBrokerEndpointConnector_Expecter) Connect(ctx any, endpoint any) *MockBrokerEndpointConnector_Connect_Call {
	return &MockBrokerEndpointConnector_Connect_Call{Call: _e.mock.On("Connect", ctx, endpoint)}
}

func (_c *MockBrokerEndpointConnector_Connect_Call) Run(run func(ctx context.Context, endpoint ports.BrokerResolvedEndpoint)) *MockBrokerEndpointConnector_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.BrokerResolvedEndpoint
		if args[1] != nil {
			arg1 = args[1].(ports.BrokerResolvedEndpoint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerEndpointConnector_Connect_Call) Return(brokerPhysicalConnection ports.BrokerPhysicalConnection, err error) *MockBrokerEndpointConnector_Connect_Call {
	_c.Call.Return(brokerPhysicalConnection, err)
	return _c
}

func (_c *MockBrokerEndpointConnector_Connect_Call) RunAndReturn(run func(ctx context.Context, endpoint ports.BrokerResolvedEndpoint) (ports.BrokerPhysicalConnection, error)) *MockBrokerEndpointConnector_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerConnector creates a new instance of MockBrokerConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerConnector {
	mock := &MockBrokerConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerConnector is an autogenerated mock type for the BrokerConnector type
type MockBrokerConnector struct {
	mock.Mock
}

type MockBrokerConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerConnector) EXPECT() *MockBrokerConnector_Expecter {
	return &MockBrokerConnector_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockBrokerConnector
func (_mock *MockBrokerConnector) Connect(ctx context.Context) (ports.BrokerService, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 ports.BrokerService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.BrokerService, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.BrokerService); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerConnector_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockBrokerConnector_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBrokerConnector_Expecter) Connect(ctx any) *MockBrokerConnector_Connect_Call {
	return &MockBrokerConnector_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *MockBrokerConnector_Connect_Call) Run(run func(ctx context.Context)) *MockBrokerConnector_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBrokerConnector_Connect_Call) Return(brokerService ports.BrokerService, err error) *MockBrokerConnector_Connect_Call {
	_c.Call.Return(brokerService, err)
	return _c
}

func (_c *MockBrokerConnector_Connect_Call) RunAndReturn(run func(ctx context.Context) (ports.BrokerService, error)) *MockBrokerConnector_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerAuthority creates a new instance of MockBrokerAuthority. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerAuthority(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerAuthority {
	mock := &MockBrokerAuthority{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerAuthority is an autogenerated mock type for the BrokerAuthority type
type MockBrokerAuthority struct {
	mock.Mock
}

type MockBrokerAuthority_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerAuthority) EXPECT() *MockBrokerAuthority_Expecter {
	return &MockBrokerAuthority_Expecter{mock: &_m.Mock}
}

// AdmitClient provides a mock function for the type MockBrokerAuthority
func (_mock *MockBrokerAuthority) AdmitClient(ctx context.Context) (ports.BrokerService, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AdmitClient")
	}

	var r0 ports.BrokerService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.BrokerService, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.BrokerService); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerAuthority_AdmitClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmitClient'
type MockBrokerAuthority_AdmitClient_Call struct {
	*mock.Call
}

// AdmitClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBrokerAuthority_Expecter) AdmitClient(ctx any) *MockBrokerAuthority_AdmitClient_Call {
	return &MockBrokerAuthority_AdmitClient_Call{Call: _e.mock.On("AdmitClient", ctx)}
}

func (_c *MockBrokerAuthority_AdmitClient_Call) Run(run func(ctx context.Context)) *MockBrokerAuthority_AdmitClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBrokerAuthority_AdmitClient_Call) Return(brokerService ports.BrokerService, err error) *MockBrokerAuthority_AdmitClient_Call {
	_c.Call.Return(brokerService, err)
	return _c
}

func (_c *MockBrokerAuthority_AdmitClient_Call) RunAndReturn(run func(ctx context.Context) (ports.BrokerService, error)) *MockBrokerAuthority_AdmitClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrokerListener creates a new instance of MockBrokerListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerListener {
	mock := &MockBrokerListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerListener is an autogenerated mock type for the BrokerListener type
type MockBrokerListener struct {
	mock.Mock
}

type MockBrokerListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerListener) EXPECT() *MockBrokerListener_Expecter {
	return &MockBrokerListener_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockBrokerListener
func (_mock *MockBrokerListener) Accept() (ports.BrokerService, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 ports.BrokerService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (ports.BrokerService, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() ports.BrokerService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BrokerService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerListener_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockBrokerListener_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
func (_e *MockBrokerListener_Expecter) Accept() *MockBrokerListener_Accept_Call {
	return &MockBrokerListener_Accept_Call{Call: _e.mock.On("Accept")}
}

func (_c *MockBrokerListener_Accept_Call) Run(run func()) *MockBrokerListener_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerListener_Accept_Call) Return(brokerService ports.BrokerService, err error) *MockBrokerListener_Accept_Call {
	_c.Call.Return(brokerService, err)
	return _c
}

func (_c *MockBrokerListener_Accept_Call) RunAndReturn(run func() (ports.BrokerService, error)) *MockBrokerListener_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Addr provides a mock function for the type MockBrokerListener
func (_mock *MockBrokerListener) Addr() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addr")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBrokerListener_Addr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addr'
type MockBrokerListener_Addr_Call struct {
	*mock.Call
}

// Addr is a helper method to define mock.On call
func (_e *MockBrokerListener_Expecter) Addr() *MockBrokerListener_Addr_Call {
	return &MockBrokerListener_Addr_Call{Call: _e.mock.On("Addr")}
}

func (_c *MockBrokerListener_Addr_Call) Run(run func()) *MockBrokerListener_Addr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerListener_Addr_Call) Return(s string) *MockBrokerListener_Addr_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBrokerListener_Addr_Call) RunAndReturn(run func() string) *MockBrokerListener_Addr_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBrokerListener
func (_mock *MockBrokerListener) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerListener_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBrokerListener_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBrokerListener_Expecter) Close() *MockBrokerListener_Close_Call {
	return &MockBrokerListener_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBrokerListener_Close_Call) Run(run func()) *MockBrokerListener_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerListener_Close_Call) Return(err error) *MockBrokerListener_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerListener_Close_Call) RunAndReturn(run func() error) *MockBrokerListener_Close_Call {
	_c.Call.Return(run)
	return _c
}
