// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"github.com/bnema/vev/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNoticeStore creates a new instance of MockNoticeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoticeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoticeStore {
	mock := &MockNoticeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoticeStore is an autogenerated mock type for the NoticeStore type
type MockNoticeStore struct {
	mock.Mock
}

type MockNoticeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoticeStore) EXPECT() *MockNoticeStore_Expecter {
	return &MockNoticeStore_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockNoticeStore
func (_mock *MockNoticeStore) Append(n domain.Notification) error {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.Notification) error); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoticeStore_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockNoticeStore_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - n domain.Notification
func (_e *MockNoticeStore_Expecter) Append(n any) *MockNoticeStore_Append_Call {
	return &MockNoticeStore_Append_Call{Call: _e.mock.On("Append", n)}
}

func (_c *MockNoticeStore_Append_Call) Run(run func(n domain.Notification)) *MockNoticeStore_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Notification
		if args[0] != nil {
			arg0 = args[0].(domain.Notification)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNoticeStore_Append_Call) Return(err error) *MockNoticeStore_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoticeStore_Append_Call) RunAndReturn(run func(n domain.Notification) error) *MockNoticeStore_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Drain provides a mock function for the type MockNoticeStore
func (_mock *MockNoticeStore) Drain() ([]domain.Notification, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 []domain.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.Notification, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.Notification); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoticeStore_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type MockNoticeStore_Drain_Call struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
func (_e *MockNoticeStore_Expecter) Drain() *MockNoticeStore_Drain_Call {
	return &MockNoticeStore_Drain_Call{Call: _e.mock.On("Drain")}
}

func (_c *MockNoticeStore_Drain_Call) Run(run func()) *MockNoticeStore_Drain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNoticeStore_Drain_Call) Return(notifications []domain.Notification, err error) *MockNoticeStore_Drain_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockNoticeStore_Drain_Call) RunAndReturn(run func() ([]domain.Notification, error)) *MockNoticeStore_Drain_Call {
	_c.Call.Return(run)
	return _c
}
