// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/bnema/vev/internal/domain"
	"github.com/bnema/vev/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSnapshotMigration creates a new instance of MockSnapshotMigration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotMigration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotMigration {
	mock := &MockSnapshotMigration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotMigration is an autogenerated mock type for the SnapshotMigration type
type MockSnapshotMigration struct {
	mock.Mock
}

type MockSnapshotMigration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotMigration) EXPECT() *MockSnapshotMigration_Expecter {
	return &MockSnapshotMigration_Expecter{mock: &_m.Mock}
}

// HasLegacyState provides a mock function for the type MockSnapshotMigration
func (_mock *MockSnapshotMigration) HasLegacyState(context1 context.Context) (bool, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for HasLegacyState")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotMigration_HasLegacyState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasLegacyState'
type MockSnapshotMigration_HasLegacyState_Call struct {
	*mock.Call
}

// HasLegacyState is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockSnapshotMigration_Expecter) HasLegacyState(context1 any) *MockSnapshotMigration_HasLegacyState_Call {
	return &MockSnapshotMigration_HasLegacyState_Call{Call: _e.mock.On("HasLegacyState", context1)}
}

func (_c *MockSnapshotMigration_HasLegacyState_Call) Run(run func(context1 context.Context)) *MockSnapshotMigration_HasLegacyState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSnapshotMigration_HasLegacyState_Call) Return(b bool, err error) *MockSnapshotMigration_HasLegacyState_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSnapshotMigration_HasLegacyState_Call) RunAndReturn(run func(context1 context.Context) (bool, error)) *MockSnapshotMigration_HasLegacyState_Call {
	_c.Call.Return(run)
	return _c
}

// MigrateV1Checkpoint provides a mock function for the type MockSnapshotMigration
func (_mock *MockSnapshotMigration) MigrateV1Checkpoint(context1 context.Context, snapshotMigrationRequest ports.SnapshotMigrationRequest) (domain.CheckpointRef, error) {
	ret := _mock.Called(context1, snapshotMigrationRequest)

	if len(ret) == 0 {
		panic("no return value specified for MigrateV1Checkpoint")
	}

	var r0 domain.CheckpointRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.SnapshotMigrationRequest) (domain.CheckpointRef, error)); ok {
		return returnFunc(context1, snapshotMigrationRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.SnapshotMigrationRequest) domain.CheckpointRef); ok {
		r0 = returnFunc(context1, snapshotMigrationRequest)
	} else {
		r0 = ret.Get(0).(domain.CheckpointRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.SnapshotMigrationRequest) error); ok {
		r1 = returnFunc(context1, snapshotMigrationRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotMigration_MigrateV1Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrateV1Checkpoint'
type MockSnapshotMigration_MigrateV1Checkpoint_Call struct {
	*mock.Call
}

// MigrateV1Checkpoint is a helper method to define mock.On call
//   - context1 context.Context
//   - snapshotMigrationRequest ports.SnapshotMigrationRequest
func (_e *MockSnapshotMigration_Expecter) MigrateV1Checkpoint(context1 any, snapshotMigrationRequest any) *MockSnapshotMigration_MigrateV1Checkpoint_Call {
	return &MockSnapshotMigration_MigrateV1Checkpoint_Call{Call: _e.mock.On("MigrateV1Checkpoint", context1, snapshotMigrationRequest)}
}

func (_c *MockSnapshotMigration_MigrateV1Checkpoint_Call) Run(run func(context1 context.Context, snapshotMigrationRequest ports.SnapshotMigrationRequest)) *MockSnapshotMigration_MigrateV1Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.SnapshotMigrationRequest
		if args[1] != nil {
			arg1 = args[1].(ports.SnapshotMigrationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotMigration_MigrateV1Checkpoint_Call) Return(checkpointRef domain.CheckpointRef, err error) *MockSnapshotMigration_MigrateV1Checkpoint_Call {
	_c.Call.Return(checkpointRef, err)
	return _c
}

func (_c *MockSnapshotMigration_MigrateV1Checkpoint_Call) RunAndReturn(run func(context1 context.Context, snapshotMigrationRequest ports.SnapshotMigrationRequest) (domain.CheckpointRef, error)) *MockSnapshotMigration_MigrateV1Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}

// ReadLegacyHEAD provides a mock function for the type MockSnapshotMigration
func (_mock *MockSnapshotMigration) ReadLegacyHEAD(context1 context.Context, s string) (domain.CheckpointRef, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ReadLegacyHEAD")
	}

	var r0 domain.CheckpointRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.CheckpointRef, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.CheckpointRef); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(domain.CheckpointRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotMigration_ReadLegacyHEAD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadLegacyHEAD'
type MockSnapshotMigration_ReadLegacyHEAD_Call struct {
	*mock.Call
}

// ReadLegacyHEAD is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockSnapshotMigration_Expecter) ReadLegacyHEAD(context1 any, s any) *MockSnapshotMigration_ReadLegacyHEAD_Call {
	return &MockSnapshotMigration_ReadLegacyHEAD_Call{Call: _e.mock.On("ReadLegacyHEAD", context1, s)}
}

func (_c *MockSnapshotMigration_ReadLegacyHEAD_Call) Run(run func(context1 context.Context, s string)) *MockSnapshotMigration_ReadLegacyHEAD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotMigration_ReadLegacyHEAD_Call) Return(checkpointRef domain.CheckpointRef, err error) *MockSnapshotMigration_ReadLegacyHEAD_Call {
	_c.Call.Return(checkpointRef, err)
	return _c
}

func (_c *MockSnapshotMigration_ReadLegacyHEAD_Call) RunAndReturn(run func(context1 context.Context, s string) (domain.CheckpointRef, error)) *MockSnapshotMigration_ReadLegacyHEAD_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecoveryJournal creates a new instance of MockRecoveryJournal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecoveryJournal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecoveryJournal {
	mock := &MockRecoveryJournal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecoveryJournal is an autogenerated mock type for the RecoveryJournal type
type MockRecoveryJournal struct {
	mock.Mock
}

type MockRecoveryJournal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecoveryJournal) EXPECT() *MockRecoveryJournal_Expecter {
	return &MockRecoveryJournal_Expecter{mock: &_m.Mock}
}

// DeleteDiscard provides a mock function for the type MockRecoveryJournal
func (_mock *MockRecoveryJournal) DeleteDiscard(context1 context.Context, incarnationID domain.IncarnationID) error {
	ret := _mock.Called(context1, incarnationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDiscard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IncarnationID) error); ok {
		r0 = returnFunc(context1, incarnationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecoveryJournal_DeleteDiscard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDiscard'
type MockRecoveryJournal_DeleteDiscard_Call struct {
	*mock.Call
}

// DeleteDiscard is a helper method to define mock.On call
//   - context1 context.Context
//   - incarnationID domain.IncarnationID
func (_e *MockRecoveryJournal_Expecter) DeleteDiscard(context1 any, incarnationID any) *MockRecoveryJournal_DeleteDiscard_Call {
	return &MockRecoveryJournal_DeleteDiscard_Call{Call: _e.mock.On("DeleteDiscard", context1, incarnationID)}
}

func (_c *MockRecoveryJournal_DeleteDiscard_Call) Run(run func(context1 context.Context, incarnationID domain.IncarnationID)) *MockRecoveryJournal_DeleteDiscard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IncarnationID
		if args[1] != nil {
			arg1 = args[1].(domain.IncarnationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecoveryJournal_DeleteDiscard_Call) Return(err error) *MockRecoveryJournal_DeleteDiscard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecoveryJournal_DeleteDiscard_Call) RunAndReturn(run func(context1 context.Context, incarnationID domain.IncarnationID) error) *MockRecoveryJournal_DeleteDiscard_Call {
	_c.Call.Return(run)
	return _c
}

// ListDiscards provides a mock function for the type MockRecoveryJournal
func (_mock *MockRecoveryJournal) ListDiscards(context1 context.Context) ([]domain.DiscardIntent, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListDiscards")
	}

	var r0 []domain.DiscardIntent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.DiscardIntent, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.DiscardIntent); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DiscardIntent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRecoveryJournal_ListDiscards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDiscards'
type MockRecoveryJournal_ListDiscards_Call struct {
	*mock.Call
}

// ListDiscards is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRecoveryJournal_Expecter) ListDiscards(context1 any) *MockRecoveryJournal_ListDiscards_Call {
	return &MockRecoveryJournal_ListDiscards_Call{Call: _e.mock.On("ListDiscards", context1)}
}

func (_c *MockRecoveryJournal_ListDiscards_Call) Run(run func(context1 context.Context)) *MockRecoveryJournal_ListDiscards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecoveryJournal_ListDiscards_Call) Return(discardIntents []domain.DiscardIntent, err error) *MockRecoveryJournal_ListDiscards_Call {
	_c.Call.Return(discardIntents, err)
	return _c
}

func (_c *MockRecoveryJournal_ListDiscards_Call) RunAndReturn(run func(context1 context.Context) ([]domain.DiscardIntent, error)) *MockRecoveryJournal_ListDiscards_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDiscard provides a mock function for the type MockRecoveryJournal
func (_mock *MockRecoveryJournal) SaveDiscard(context1 context.Context, discardIntent domain.DiscardIntent) error {
	ret := _mock.Called(context1, discardIntent)

	if len(ret) == 0 {
		panic("no return value specified for SaveDiscard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DiscardIntent) error); ok {
		r0 = returnFunc(context1, discardIntent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecoveryJournal_SaveDiscard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDiscard'
type MockRecoveryJournal_SaveDiscard_Call struct {
	*mock.Call
}

// SaveDiscard is a helper method to define mock.On call
//   - context1 context.Context
//   - discardIntent domain.DiscardIntent
func (_e *MockRecoveryJournal_Expecter) SaveDiscard(context1 any, discardIntent any) *MockRecoveryJournal_SaveDiscard_Call {
	return &MockRecoveryJournal_SaveDiscard_Call{Call: _e.mock.On("SaveDiscard", context1, discardIntent)}
}

func (_c *MockRecoveryJournal_SaveDiscard_Call) Run(run func(context1 context.Context, discardIntent domain.DiscardIntent)) *MockRecoveryJournal_SaveDiscard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DiscardIntent
		if args[1] != nil {
			arg1 = args[1].(domain.DiscardIntent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecoveryJournal_SaveDiscard_Call) Return(err error) *MockRecoveryJournal_SaveDiscard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecoveryJournal_SaveDiscard_Call) RunAndReturn(run func(context1 context.Context, discardIntent domain.DiscardIntent) error) *MockRecoveryJournal_SaveDiscard_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogue creates a new instance of MockCatalogue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogue {
	mock := &MockCatalogue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogue is an autogenerated mock type for the Catalogue type
type MockCatalogue struct {
	mock.Mock
}

type MockCatalogue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogue) EXPECT() *MockCatalogue_Expecter {
	return &MockCatalogue_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCatalogue
func (_mock *MockCatalogue) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCatalogue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCatalogue_Expecter) Close() *MockCatalogue_Close_Call {
	return &MockCatalogue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCatalogue_Close_Call) Run(run func()) *MockCatalogue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogue_Close_Call) Return(err error) *MockCatalogue_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogue_Close_Call) RunAndReturn(run func() error) *MockCatalogue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockCatalogue
func (_mock *MockCatalogue) Create(catalogueRecord domain.CatalogueRecord) error {
	ret := _mock.Called(catalogueRecord)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.CatalogueRecord) error); ok {
		r0 = returnFunc(catalogueRecord)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogue_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCatalogue_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - catalogueRecord domain.CatalogueRecord
func (_e *MockCatalogue_Expecter) Create(catalogueRecord any) *MockCatalogue_Create_Call {
	return &MockCatalogue_Create_Call{Call: _e.mock.On("Create", catalogueRecord)}
}

func (_c *MockCatalogue_Create_Call) Run(run func(catalogueRecord domain.CatalogueRecord)) *MockCatalogue_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.CatalogueRecord
		if args[0] != nil {
			arg0 = args[0].(domain.CatalogueRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogue_Create_Call) Return(err error) *MockCatalogue_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogue_Create_Call) RunAndReturn(run func(catalogueRecord domain.CatalogueRecord) error) *MockCatalogue_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCatalogue
func (_mock *MockCatalogue) Delete(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogue_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCatalogue_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - s string
func (_e *MockCatalogue_Expecter) Delete(s any) *MockCatalogue_Delete_Call {
	return &MockCatalogue_Delete_Call{Call: _e.mock.On("Delete", s)}
}

func (_c *MockCatalogue_Delete_Call) Run(run func(s string)) *MockCatalogue_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogue_Delete_Call) Return(err error) *MockCatalogue_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogue_Delete_Call) RunAndReturn(run func(s string) error) *MockCatalogue_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function for the type MockCatalogue
func (_mock *MockCatalogue) Record(s string) (domain.CatalogueRecord, bool) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 domain.CatalogueRecord
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (domain.CatalogueRecord, bool)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.CatalogueRecord); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(domain.CatalogueRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCatalogue_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockCatalogue_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - s string
func (_e *MockCatalogue_Expecter) Record(s any) *MockCatalogue_Record_Call {
	return &MockCatalogue_Record_Call{Call: _e.mock.On("Record", s)}
}

func (_c *MockCatalogue_Record_Call) Run(run func(s string)) *MockCatalogue_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogue_Record_Call) Return(catalogueRecord domain.CatalogueRecord, b bool) *MockCatalogue_Record_Call {
	_c.Call.Return(catalogueRecord, b)
	return _c
}

func (_c *MockCatalogue_Record_Call) RunAndReturn(run func(s string) (domain.CatalogueRecord, bool)) *MockCatalogue_Record_Call {
	_c.Call.Return(run)
	return _c
}

// Records provides a mock function for the type MockCatalogue
func (_mock *MockCatalogue) Records() []domain.CatalogueRecord {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Records")
	}

	var r0 []domain.CatalogueRecord
	if returnFunc, ok := ret.Get(0).(func() []domain.CatalogueRecord); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CatalogueRecord)
		}
	}
	return r0
}

// MockCatalogue_Records_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Records'
type MockCatalogue_Records_Call struct {
	*mock.Call
}

// Records is a helper method to define mock.On call
func (_e *MockCatalogue_Expecter) Records() *MockCatalogue_Records_Call {
	return &MockCatalogue_Records_Call{Call: _e.mock.On("Records")}
}

func (_c *MockCatalogue_Records_Call) Run(run func()) *MockCatalogue_Records_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogue_Records_Call) Return(catalogueRecords []domain.CatalogueRecord) *MockCatalogue_Records_Call {
	_c.Call.Return(catalogueRecords)
	return _c
}

func (_c *MockCatalogue_Records_Call) RunAndReturn(run func() []domain.CatalogueRecord) *MockCatalogue_Records_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockCatalogue
func (_mock *MockCatalogue) Rename(s string, catalogueRecord domain.CatalogueRecord) error {
	ret := _mock.Called(s, catalogueRecord)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.CatalogueRecord) error); ok {
		r0 = returnFunc(s, catalogueRecord)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogue_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockCatalogue_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - s string
//   - catalogueRecord domain.CatalogueRecord
func (_e *MockCatalogue_Expecter) Rename(s any, catalogueRecord any) *MockCatalogue_Rename_Call {
	return &MockCatalogue_Rename_Call{Call: _e.mock.On("Rename", s, catalogueRecord)}
}

func (_c *MockCatalogue_Rename_Call) Run(run func(s string, catalogueRecord domain.CatalogueRecord)) *MockCatalogue_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.CatalogueRecord
		if args[1] != nil {
			arg1 = args[1].(domain.CatalogueRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogue_Rename_Call) Return(err error) *MockCatalogue_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogue_Rename_Call) RunAndReturn(run func(s string, catalogueRecord domain.CatalogueRecord) error) *MockCatalogue_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockCatalogue
func (_mock *MockCatalogue) Replace(s string, catalogueRecord domain.CatalogueRecord) error {
	ret := _mock.Called(s, catalogueRecord)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.CatalogueRecord) error); ok {
		r0 = returnFunc(s, catalogueRecord)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogue_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockCatalogue_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - s string
//   - catalogueRecord domain.CatalogueRecord
func (_e *MockCatalogue_Expecter) Replace(s any, catalogueRecord any) *MockCatalogue_Replace_Call {
	return &MockCatalogue_Replace_Call{Call: _e.mock.On("Replace", s, catalogueRecord)}
}

func (_c *MockCatalogue_Replace_Call) Run(run func(s string, catalogueRecord domain.CatalogueRecord)) *MockCatalogue_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.CatalogueRecord
		if args[1] != nil {
			arg1 = args[1].(domain.CatalogueRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogue_Replace_Call) Return(err error) *MockCatalogue_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogue_Replace_Call) RunAndReturn(run func(s string, catalogueRecord domain.CatalogueRecord) error) *MockCatalogue_Replace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnapshotRepository creates a new instance of MockSnapshotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotRepository {
	mock := &MockSnapshotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotRepository is an autogenerated mock type for the SnapshotRepository type
type MockSnapshotRepository struct {
	mock.Mock
}

type MockSnapshotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotRepository) EXPECT() *MockSnapshotRepository_Expecter {
	return &MockSnapshotRepository_Expecter{mock: &_m.Mock}
}

// DeleteDeletionTombstone provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) DeleteDeletionTombstone(context1 context.Context, incarnationID domain.IncarnationID) error {
	ret := _mock.Called(context1, incarnationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeletionTombstone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IncarnationID) error); ok {
		r0 = returnFunc(context1, incarnationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_DeleteDeletionTombstone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeletionTombstone'
type MockSnapshotRepository_DeleteDeletionTombstone_Call struct {
	*mock.Call
}

// DeleteDeletionTombstone is a helper method to define mock.On call
//   - context1 context.Context
//   - incarnationID domain.IncarnationID
func (_e *MockSnapshotRepository_Expecter) DeleteDeletionTombstone(context1 any, incarnationID any) *MockSnapshotRepository_DeleteDeletionTombstone_Call {
	return &MockSnapshotRepository_DeleteDeletionTombstone_Call{Call: _e.mock.On("DeleteDeletionTombstone", context1, incarnationID)}
}

func (_c *MockSnapshotRepository_DeleteDeletionTombstone_Call) Run(run func(context1 context.Context, incarnationID domain.IncarnationID)) *MockSnapshotRepository_DeleteDeletionTombstone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IncarnationID
		if args[1] != nil {
			arg1 = args[1].(domain.IncarnationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_DeleteDeletionTombstone_Call) Return(err error) *MockSnapshotRepository_DeleteDeletionTombstone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_DeleteDeletionTombstone_Call) RunAndReturn(run func(context1 context.Context, incarnationID domain.IncarnationID) error) *MockSnapshotRepository_DeleteDeletionTombstone_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIncarnation provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) DeleteIncarnation(context1 context.Context, incarnationID domain.IncarnationID) error {
	ret := _mock.Called(context1, incarnationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIncarnation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IncarnationID) error); ok {
		r0 = returnFunc(context1, incarnationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_DeleteIncarnation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIncarnation'
type MockSnapshotRepository_DeleteIncarnation_Call struct {
	*mock.Call
}

// DeleteIncarnation is a helper method to define mock.On call
//   - context1 context.Context
//   - incarnationID domain.IncarnationID
func (_e *MockSnapshotRepository_Expecter) DeleteIncarnation(context1 any, incarnationID any) *MockSnapshotRepository_DeleteIncarnation_Call {
	return &MockSnapshotRepository_DeleteIncarnation_Call{Call: _e.mock.On("DeleteIncarnation", context1, incarnationID)}
}

func (_c *MockSnapshotRepository_DeleteIncarnation_Call) Run(run func(context1 context.Context, incarnationID domain.IncarnationID)) *MockSnapshotRepository_DeleteIncarnation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IncarnationID
		if args[1] != nil {
			arg1 = args[1].(domain.IncarnationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_DeleteIncarnation_Call) Return(err error) *MockSnapshotRepository_DeleteIncarnation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_DeleteIncarnation_Call) RunAndReturn(run func(context1 context.Context, incarnationID domain.IncarnationID) error) *MockSnapshotRepository_DeleteIncarnation_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeletionTombstones provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) ListDeletionTombstones(context1 context.Context, deletionTombstoneCursor ports.DeletionTombstoneCursor, maintenanceBudget ports.MaintenanceBudget) (ports.DeletionTombstonePage, error) {
	ret := _mock.Called(context1, deletionTombstoneCursor, maintenanceBudget)

	if len(ret) == 0 {
		panic("no return value specified for ListDeletionTombstones")
	}

	var r0 ports.DeletionTombstonePage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.DeletionTombstoneCursor, ports.MaintenanceBudget) (ports.DeletionTombstonePage, error)); ok {
		return returnFunc(context1, deletionTombstoneCursor, maintenanceBudget)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.DeletionTombstoneCursor, ports.MaintenanceBudget) ports.DeletionTombstonePage); ok {
		r0 = returnFunc(context1, deletionTombstoneCursor, maintenanceBudget)
	} else {
		r0 = ret.Get(0).(ports.DeletionTombstonePage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.DeletionTombstoneCursor, ports.MaintenanceBudget) error); ok {
		r1 = returnFunc(context1, deletionTombstoneCursor, maintenanceBudget)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotRepository_ListDeletionTombstones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeletionTombstones'
type MockSnapshotRepository_ListDeletionTombstones_Call struct {
	*mock.Call
}

// ListDeletionTombstones is a helper method to define mock.On call
//   - context1 context.Context
//   - deletionTombstoneCursor ports.DeletionTombstoneCursor
//   - maintenanceBudget ports.MaintenanceBudget
func (_e *MockSnapshotRepository_Expecter) ListDeletionTombstones(context1 any, deletionTombstoneCursor any, maintenanceBudget any) *MockSnapshotRepository_ListDeletionTombstones_Call {
	return &MockSnapshotRepository_ListDeletionTombstones_Call{Call: _e.mock.On("ListDeletionTombstones", context1, deletionTombstoneCursor, maintenanceBudget)}
}

func (_c *MockSnapshotRepository_ListDeletionTombstones_Call) Run(run func(context1 context.Context, deletionTombstoneCursor ports.DeletionTombstoneCursor, maintenanceBudget ports.MaintenanceBudget)) *MockSnapshotRepository_ListDeletionTombstones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.DeletionTombstoneCursor
		if args[1] != nil {
			arg1 = args[1].(ports.DeletionTombstoneCursor)
		}
		var arg2 ports.MaintenanceBudget
		if args[2] != nil {
			arg2 = args[2].(ports.MaintenanceBudget)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_ListDeletionTombstones_Call) Return(deletionTombstonePage ports.DeletionTombstonePage, err error) *MockSnapshotRepository_ListDeletionTombstones_Call {
	_c.Call.Return(deletionTombstonePage, err)
	return _c
}

func (_c *MockSnapshotRepository_ListDeletionTombstones_Call) RunAndReturn(run func(context1 context.Context, deletionTombstoneCursor ports.DeletionTombstoneCursor, maintenanceBudget ports.MaintenanceBudget) (ports.DeletionTombstonePage, error)) *MockSnapshotRepository_ListDeletionTombstones_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCheckpoint provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) LoadCheckpoint(context1 context.Context, incarnationID domain.IncarnationID, s string, v ports.CheckpointRef) (ports.SnapshotGeneration, error) {
	ret := _mock.Called(context1, incarnationID, s, v)

	if len(ret) == 0 {
		panic("no return value specified for LoadCheckpoint")
	}

	var r0 ports.SnapshotGeneration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IncarnationID, string, ports.CheckpointRef) (ports.SnapshotGeneration, error)); ok {
		return returnFunc(context1, incarnationID, s, v)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IncarnationID, string, ports.CheckpointRef) ports.SnapshotGeneration); ok {
		r0 = returnFunc(context1, incarnationID, s, v)
	} else {
		r0 = ret.Get(0).(ports.SnapshotGeneration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.IncarnationID, string, ports.CheckpointRef) error); ok {
		r1 = returnFunc(context1, incarnationID, s, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotRepository_LoadCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCheckpoint'
type MockSnapshotRepository_LoadCheckpoint_Call struct {
	*mock.Call
}

// LoadCheckpoint is a helper method to define mock.On call
//   - context1 context.Context
//   - incarnationID domain.IncarnationID
//   - s string
//   - v ports.CheckpointRef
func (_e *MockSnapshotRepository_Expecter) LoadCheckpoint(context1 any, incarnationID any, s any, v any) *MockSnapshotRepository_LoadCheckpoint_Call {
	return &MockSnapshotRepository_LoadCheckpoint_Call{Call: _e.mock.On("LoadCheckpoint", context1, incarnationID, s, v)}
}

func (_c *MockSnapshotRepository_LoadCheckpoint_Call) Run(run func(context1 context.Context, incarnationID domain.IncarnationID, s string, v ports.CheckpointRef)) *MockSnapshotRepository_LoadCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IncarnationID
		if args[1] != nil {
			arg1 = args[1].(domain.IncarnationID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 ports.CheckpointRef
		if args[3] != nil {
			arg3 = args[3].(ports.CheckpointRef)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_LoadCheckpoint_Call) Return(snapshotGeneration ports.SnapshotGeneration, err error) *MockSnapshotRepository_LoadCheckpoint_Call {
	_c.Call.Return(snapshotGeneration, err)
	return _c
}

func (_c *MockSnapshotRepository_LoadCheckpoint_Call) RunAndReturn(run func(context1 context.Context, incarnationID domain.IncarnationID, s string, v ports.CheckpointRef) (ports.SnapshotGeneration, error)) *MockSnapshotRepository_LoadCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// MaintainSession provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) MaintainSession(context1 context.Context, retentionPlan ports.RetentionPlan, maintenanceBudget ports.MaintenanceBudget) (bool, error) {
	ret := _mock.Called(context1, retentionPlan, maintenanceBudget)

	if len(ret) == 0 {
		panic("no return value specified for MaintainSession")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.RetentionPlan, ports.MaintenanceBudget) (bool, error)); ok {
		return returnFunc(context1, retentionPlan, maintenanceBudget)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.RetentionPlan, ports.MaintenanceBudget) bool); ok {
		r0 = returnFunc(context1, retentionPlan, maintenanceBudget)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.RetentionPlan, ports.MaintenanceBudget) error); ok {
		r1 = returnFunc(context1, retentionPlan, maintenanceBudget)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotRepository_MaintainSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaintainSession'
type MockSnapshotRepository_MaintainSession_Call struct {
	*mock.Call
}

// MaintainSession is a helper method to define mock.On call
//   - context1 context.Context
//   - retentionPlan ports.RetentionPlan
//   - maintenanceBudget ports.MaintenanceBudget
func (_e *MockSnapshotRepository_Expecter) MaintainSession(context1 any, retentionPlan any, maintenanceBudget any) *MockSnapshotRepository_MaintainSession_Call {
	return &MockSnapshotRepository_MaintainSession_Call{Call: _e.mock.On("MaintainSession", context1, retentionPlan, maintenanceBudget)}
}

func (_c *MockSnapshotRepository_MaintainSession_Call) Run(run func(context1 context.Context, retentionPlan ports.RetentionPlan, maintenanceBudget ports.MaintenanceBudget)) *MockSnapshotRepository_MaintainSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.RetentionPlan
		if args[1] != nil {
			arg1 = args[1].(ports.RetentionPlan)
		}
		var arg2 ports.MaintenanceBudget
		if args[2] != nil {
			arg2 = args[2].(ports.MaintenanceBudget)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_MaintainSession_Call) Return(b bool, err error) *MockSnapshotRepository_MaintainSession_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSnapshotRepository_MaintainSession_Call) RunAndReturn(run func(context1 context.Context, retentionPlan ports.RetentionPlan, maintenanceBudget ports.MaintenanceBudget) (bool, error)) *MockSnapshotRepository_MaintainSession_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) Publish(context1 context.Context, snapshotPublication ports.SnapshotPublication) error {
	ret := _mock.Called(context1, snapshotPublication)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.SnapshotPublication) error); ok {
		r0 = returnFunc(context1, snapshotPublication)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockSnapshotRepository_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - context1 context.Context
//   - snapshotPublication ports.SnapshotPublication
func (_e *MockSnapshotRepository_Expecter) Publish(context1 any, snapshotPublication any) *MockSnapshotRepository_Publish_Call {
	return &MockSnapshotRepository_Publish_Call{Call: _e.mock.On("Publish", context1, snapshotPublication)}
}

func (_c *MockSnapshotRepository_Publish_Call) Run(run func(context1 context.Context, snapshotPublication ports.SnapshotPublication)) *MockSnapshotRepository_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.SnapshotPublication
		if args[1] != nil {
			arg1 = args[1].(ports.SnapshotPublication)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_Publish_Call) Return(err error) *MockSnapshotRepository_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_Publish_Call) RunAndReturn(run func(context1 context.Context, snapshotPublication ports.SnapshotPublication) error) *MockSnapshotRepository_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// QuarantineDeletionSources provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) QuarantineDeletionSources(context1 context.Context, deletionTombstone domain.DeletionTombstone, b bool) error {
	ret := _mock.Called(context1, deletionTombstone, b)

	if len(ret) == 0 {
		panic("no return value specified for QuarantineDeletionSources")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DeletionTombstone, bool) error); ok {
		r0 = returnFunc(context1, deletionTombstone, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_QuarantineDeletionSources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuarantineDeletionSources'
type MockSnapshotRepository_QuarantineDeletionSources_Call struct {
	*mock.Call
}

// QuarantineDeletionSources is a helper method to define mock.On call
//   - context1 context.Context
//   - deletionTombstone domain.DeletionTombstone
//   - b bool
func (_e *MockSnapshotRepository_Expecter) QuarantineDeletionSources(context1 any, deletionTombstone any, b any) *MockSnapshotRepository_QuarantineDeletionSources_Call {
	return &MockSnapshotRepository_QuarantineDeletionSources_Call{Call: _e.mock.On("QuarantineDeletionSources", context1, deletionTombstone, b)}
}

func (_c *MockSnapshotRepository_QuarantineDeletionSources_Call) Run(run func(context1 context.Context, deletionTombstone domain.DeletionTombstone, b bool)) *MockSnapshotRepository_QuarantineDeletionSources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DeletionTombstone
		if args[1] != nil {
			arg1 = args[1].(domain.DeletionTombstone)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_QuarantineDeletionSources_Call) Return(err error) *MockSnapshotRepository_QuarantineDeletionSources_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_QuarantineDeletionSources_Call) RunAndReturn(run func(context1 context.Context, deletionTombstone domain.DeletionTombstone, b bool) error) *MockSnapshotRepository_QuarantineDeletionSources_Call {
	_c.Call.Return(run)
	return _c
}

// QuarantineIncarnation provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) QuarantineIncarnation(context1 context.Context, incarnationID domain.IncarnationID) error {
	ret := _mock.Called(context1, incarnationID)

	if len(ret) == 0 {
		panic("no return value specified for QuarantineIncarnation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IncarnationID) error); ok {
		r0 = returnFunc(context1, incarnationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_QuarantineIncarnation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuarantineIncarnation'
type MockSnapshotRepository_QuarantineIncarnation_Call struct {
	*mock.Call
}

// QuarantineIncarnation is a helper method to define mock.On call
//   - context1 context.Context
//   - incarnationID domain.IncarnationID
func (_e *MockSnapshotRepository_Expecter) QuarantineIncarnation(context1 any, incarnationID any) *MockSnapshotRepository_QuarantineIncarnation_Call {
	return &MockSnapshotRepository_QuarantineIncarnation_Call{Call: _e.mock.On("QuarantineIncarnation", context1, incarnationID)}
}

func (_c *MockSnapshotRepository_QuarantineIncarnation_Call) Run(run func(context1 context.Context, incarnationID domain.IncarnationID)) *MockSnapshotRepository_QuarantineIncarnation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IncarnationID
		if args[1] != nil {
			arg1 = args[1].(domain.IncarnationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_QuarantineIncarnation_Call) Return(err error) *MockSnapshotRepository_QuarantineIncarnation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_QuarantineIncarnation_Call) RunAndReturn(run func(context1 context.Context, incarnationID domain.IncarnationID) error) *MockSnapshotRepository_QuarantineIncarnation_Call {
	_c.Call.Return(run)
	return _c
}

// Reconcile provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) Reconcile(context1 context.Context, catalogueRecords []domain.CatalogueRecord, reconcileCursor ports.ReconcileCursor, maintenanceBudget ports.MaintenanceBudget) (ports.ReconcileCursor, []ports.ReconcileFinding, error) {
	ret := _mock.Called(context1, catalogueRecords, reconcileCursor, maintenanceBudget)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 ports.ReconcileCursor
	var r1 []ports.ReconcileFinding
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.CatalogueRecord, ports.ReconcileCursor, ports.MaintenanceBudget) (ports.ReconcileCursor, []ports.ReconcileFinding, error)); ok {
		return returnFunc(context1, catalogueRecords, reconcileCursor, maintenanceBudget)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.CatalogueRecord, ports.ReconcileCursor, ports.MaintenanceBudget) ports.ReconcileCursor); ok {
		r0 = returnFunc(context1, catalogueRecords, reconcileCursor, maintenanceBudget)
	} else {
		r0 = ret.Get(0).(ports.ReconcileCursor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.CatalogueRecord, ports.ReconcileCursor, ports.MaintenanceBudget) []ports.ReconcileFinding); ok {
		r1 = returnFunc(context1, catalogueRecords, reconcileCursor, maintenanceBudget)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]ports.ReconcileFinding)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []domain.CatalogueRecord, ports.ReconcileCursor, ports.MaintenanceBudget) error); ok {
		r2 = returnFunc(context1, catalogueRecords, reconcileCursor, maintenanceBudget)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSnapshotRepository_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type MockSnapshotRepository_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - context1 context.Context
//   - catalogueRecords []domain.CatalogueRecord
//   - reconcileCursor ports.ReconcileCursor
//   - maintenanceBudget ports.MaintenanceBudget
func (_e *MockSnapshotRepository_Expecter) Reconcile(context1 any, catalogueRecords any, reconcileCursor any, maintenanceBudget any) *MockSnapshotRepository_Reconcile_Call {
	return &MockSnapshotRepository_Reconcile_Call{Call: _e.mock.On("Reconcile", context1, catalogueRecords, reconcileCursor, maintenanceBudget)}
}

func (_c *MockSnapshotRepository_Reconcile_Call) Run(run func(context1 context.Context, catalogueRecords []domain.CatalogueRecord, reconcileCursor ports.ReconcileCursor, maintenanceBudget ports.MaintenanceBudget)) *MockSnapshotRepository_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.CatalogueRecord
		if args[1] != nil {
			arg1 = args[1].([]domain.CatalogueRecord)
		}
		var arg2 ports.ReconcileCursor
		if args[2] != nil {
			arg2 = args[2].(ports.ReconcileCursor)
		}
		var arg3 ports.MaintenanceBudget
		if args[3] != nil {
			arg3 = args[3].(ports.MaintenanceBudget)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_Reconcile_Call) Return(reconcileCursor1 ports.ReconcileCursor, reconcileFindings []ports.ReconcileFinding, err error) *MockSnapshotRepository_Reconcile_Call {
	_c.Call.Return(reconcileCursor1, reconcileFindings, err)
	return _c
}

func (_c *MockSnapshotRepository_Reconcile_Call) RunAndReturn(run func(context1 context.Context, catalogueRecords []domain.CatalogueRecord, reconcileCursor ports.ReconcileCursor, maintenanceBudget ports.MaintenanceBudget) (ports.ReconcileCursor, []ports.ReconcileFinding, error)) *MockSnapshotRepository_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// RepairHEAD provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) RepairHEAD(context1 context.Context, incarnationID domain.IncarnationID, v ports.CheckpointRef) error {
	ret := _mock.Called(context1, incarnationID, v)

	if len(ret) == 0 {
		panic("no return value specified for RepairHEAD")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IncarnationID, ports.CheckpointRef) error); ok {
		r0 = returnFunc(context1, incarnationID, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_RepairHEAD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepairHEAD'
type MockSnapshotRepository_RepairHEAD_Call struct {
	*mock.Call
}

// RepairHEAD is a helper method to define mock.On call
//   - context1 context.Context
//   - incarnationID domain.IncarnationID
//   - v ports.CheckpointRef
func (_e *MockSnapshotRepository_Expecter) RepairHEAD(context1 any, incarnationID any, v any) *MockSnapshotRepository_RepairHEAD_Call {
	return &MockSnapshotRepository_RepairHEAD_Call{Call: _e.mock.On("RepairHEAD", context1, incarnationID, v)}
}

func (_c *MockSnapshotRepository_RepairHEAD_Call) Run(run func(context1 context.Context, incarnationID domain.IncarnationID, v ports.CheckpointRef)) *MockSnapshotRepository_RepairHEAD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IncarnationID
		if args[1] != nil {
			arg1 = args[1].(domain.IncarnationID)
		}
		var arg2 ports.CheckpointRef
		if args[2] != nil {
			arg2 = args[2].(ports.CheckpointRef)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_RepairHEAD_Call) Return(err error) *MockSnapshotRepository_RepairHEAD_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_RepairHEAD_Call) RunAndReturn(run func(context1 context.Context, incarnationID domain.IncarnationID, v ports.CheckpointRef) error) *MockSnapshotRepository_RepairHEAD_Call {
	_c.Call.Return(run)
	return _c
}

// SaveQuarantineDescriptor provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) SaveQuarantineDescriptor(context1 context.Context, quarantineDescriptor domain.QuarantineDescriptor) error {
	ret := _mock.Called(context1, quarantineDescriptor)

	if len(ret) == 0 {
		panic("no return value specified for SaveQuarantineDescriptor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.QuarantineDescriptor) error); ok {
		r0 = returnFunc(context1, quarantineDescriptor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_SaveQuarantineDescriptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveQuarantineDescriptor'
type MockSnapshotRepository_SaveQuarantineDescriptor_Call struct {
	*mock.Call
}

// SaveQuarantineDescriptor is a helper method to define mock.On call
//   - context1 context.Context
//   - quarantineDescriptor domain.QuarantineDescriptor
func (_e *MockSnapshotRepository_Expecter) SaveQuarantineDescriptor(context1 any, quarantineDescriptor any) *MockSnapshotRepository_SaveQuarantineDescriptor_Call {
	return &MockSnapshotRepository_SaveQuarantineDescriptor_Call{Call: _e.mock.On("SaveQuarantineDescriptor", context1, quarantineDescriptor)}
}

func (_c *MockSnapshotRepository_SaveQuarantineDescriptor_Call) Run(run func(context1 context.Context, quarantineDescriptor domain.QuarantineDescriptor)) *MockSnapshotRepository_SaveQuarantineDescriptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.QuarantineDescriptor
		if args[1] != nil {
			arg1 = args[1].(domain.QuarantineDescriptor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_SaveQuarantineDescriptor_Call) Return(err error) *MockSnapshotRepository_SaveQuarantineDescriptor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_SaveQuarantineDescriptor_Call) RunAndReturn(run func(context1 context.Context, quarantineDescriptor domain.QuarantineDescriptor) error) *MockSnapshotRepository_SaveQuarantineDescriptor_Call {
	_c.Call.Return(run)
	return _c
}

// WriteDeletionTombstone provides a mock function for the type MockSnapshotRepository
func (_mock *MockSnapshotRepository) WriteDeletionTombstone(context1 context.Context, deletionTombstone domain.DeletionTombstone) error {
	ret := _mock.Called(context1, deletionTombstone)

	if len(ret) == 0 {
		panic("no return value specified for WriteDeletionTombstone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DeletionTombstone) error); ok {
		r0 = returnFunc(context1, deletionTombstone)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotRepository_WriteDeletionTombstone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDeletionTombstone'
type MockSnapshotRepository_WriteDeletionTombstone_Call struct {
	*mock.Call
}

// WriteDeletionTombstone is a helper method to define mock.On call
//   - context1 context.Context
//   - deletionTombstone domain.DeletionTombstone
func (_e *MockSnapshotRepository_Expecter) WriteDeletionTombstone(context1 any, deletionTombstone any) *MockSnapshotRepository_WriteDeletionTombstone_Call {
	return &MockSnapshotRepository_WriteDeletionTombstone_Call{Call: _e.mock.On("WriteDeletionTombstone", context1, deletionTombstone)}
}

func (_c *MockSnapshotRepository_WriteDeletionTombstone_Call) Run(run func(context1 context.Context, deletionTombstone domain.DeletionTombstone)) *MockSnapshotRepository_WriteDeletionTombstone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DeletionTombstone
		if args[1] != nil {
			arg1 = args[1].(domain.DeletionTombstone)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotRepository_WriteDeletionTombstone_Call) Return(err error) *MockSnapshotRepository_WriteDeletionTombstone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotRepository_WriteDeletionTombstone_Call) RunAndReturn(run func(context1 context.Context, deletionTombstone domain.DeletionTombstone) error) *MockSnapshotRepository_WriteDeletionTombstone_Call {
	_c.Call.Return(run)
	return _c
}
