// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"
	"log/slog"

	"github.com/bnema/vev/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRemoteDialerFactory creates a new instance of MockRemoteDialerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteDialerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteDialerFactory {
	mock := &MockRemoteDialerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRemoteDialerFactory is an autogenerated mock type for the RemoteDialerFactory type
type MockRemoteDialerFactory struct {
	mock.Mock
}

type MockRemoteDialerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteDialerFactory) EXPECT() *MockRemoteDialerFactory_Expecter {
	return &MockRemoteDialerFactory_Expecter{mock: &_m.Mock}
}

// DialerForRemote provides a mock function for the type MockRemoteDialerFactory
func (_mock *MockRemoteDialerFactory) DialerForRemote(target string, session string, mode ports.RemoteTransportMode, log *slog.Logger) (ports.Dialer, error) {
	ret := _mock.Called(target, session, mode, log)

	if len(ret) == 0 {
		panic("no return value specified for DialerForRemote")
	}

	var r0 ports.Dialer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ports.RemoteTransportMode, *slog.Logger) (ports.Dialer, error)); ok {
		return returnFunc(target, session, mode, log)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ports.RemoteTransportMode, *slog.Logger) ports.Dialer); ok {
		r0 = returnFunc(target, session, mode, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.Dialer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ports.RemoteTransportMode, *slog.Logger) error); ok {
		r1 = returnFunc(target, session, mode, log)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRemoteDialerFactory_DialerForRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialerForRemote'
type MockRemoteDialerFactory_DialerForRemote_Call struct {
	*mock.Call
}

// DialerForRemote is a helper method to define mock.On call
//   - target string
//   - session string
//   - mode ports.RemoteTransportMode
//   - log *slog.Logger
func (_e *MockRemoteDialerFactory_Expecter) DialerForRemote(target any, session any, mode any, log any) *MockRemoteDialerFactory_DialerForRemote_Call {
	return &MockRemoteDialerFactory_DialerForRemote_Call{Call: _e.mock.On("DialerForRemote", target, session, mode, log)}
}

func (_c *MockRemoteDialerFactory_DialerForRemote_Call) Run(run func(target string, session string, mode ports.RemoteTransportMode, log *slog.Logger)) *MockRemoteDialerFactory_DialerForRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ports.RemoteTransportMode
		if args[2] != nil {
			arg2 = args[2].(ports.RemoteTransportMode)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRemoteDialerFactory_DialerForRemote_Call) Return(dialer ports.Dialer, err error) *MockRemoteDialerFactory_DialerForRemote_Call {
	_c.Call.Return(dialer, err)
	return _c
}

func (_c *MockRemoteDialerFactory_DialerForRemote_Call) RunAndReturn(run func(target string, session string, mode ports.RemoteTransportMode, log *slog.Logger) (ports.Dialer, error)) *MockRemoteDialerFactory_DialerForRemote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRemoteHostStore creates a new instance of MockRemoteHostStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteHostStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteHostStore {
	mock := &MockRemoteHostStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRemoteHostStore is an autogenerated mock type for the RemoteHostStore type
type MockRemoteHostStore struct {
	mock.Mock
}

type MockRemoteHostStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteHostStore) EXPECT() *MockRemoteHostStore_Expecter {
	return &MockRemoteHostStore_Expecter{mock: &_m.Mock}
}

// AddPinned provides a mock function for the type MockRemoteHostStore
func (_mock *MockRemoteHostStore) AddPinned(target string) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for AddPinned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRemoteHostStore_AddPinned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPinned'
type MockRemoteHostStore_AddPinned_Call struct {
	*mock.Call
}

// AddPinned is a helper method to define mock.On call
//   - target string
func (_e *MockRemoteHostStore_Expecter) AddPinned(target any) *MockRemoteHostStore_AddPinned_Call {
	return &MockRemoteHostStore_AddPinned_Call{Call: _e.mock.On("AddPinned", target)}
}

func (_c *MockRemoteHostStore_AddPinned_Call) Run(run func(target string)) *MockRemoteHostStore_AddPinned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRemoteHostStore_AddPinned_Call) Return(err error) *MockRemoteHostStore_AddPinned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRemoteHostStore_AddPinned_Call) RunAndReturn(run func(target string) error) *MockRemoteHostStore_AddPinned_Call {
	_c.Call.Return(run)
	return _c
}

// Forget provides a mock function for the type MockRemoteHostStore
func (_mock *MockRemoteHostStore) Forget(target string) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRemoteHostStore_Forget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forget'
type MockRemoteHostStore_Forget_Call struct {
	*mock.Call
}

// Forget is a helper method to define mock.On call
//   - target string
func (_e *MockRemoteHostStore_Expecter) Forget(target any) *MockRemoteHostStore_Forget_Call {
	return &MockRemoteHostStore_Forget_Call{Call: _e.mock.On("Forget", target)}
}

func (_c *MockRemoteHostStore_Forget_Call) Run(run func(target string)) *MockRemoteHostStore_Forget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRemoteHostStore_Forget_Call) Return(err error) *MockRemoteHostStore_Forget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRemoteHostStore_Forget_Call) RunAndReturn(run func(target string) error) *MockRemoteHostStore_Forget_Call {
	_c.Call.Return(run)
	return _c
}

// Hosts provides a mock function for the type MockRemoteHostStore
func (_mock *MockRemoteHostStore) Hosts() ([]string, []string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hosts")
	}

	var r0 []string
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, []string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []string); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRemoteHostStore_Hosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hosts'
type MockRemoteHostStore_Hosts_Call struct {
	*mock.Call
}

// Hosts is a helper method to define mock.On call
func (_e *MockRemoteHostStore_Expecter) Hosts() *MockRemoteHostStore_Hosts_Call {
	return &MockRemoteHostStore_Hosts_Call{Call: _e.mock.On("Hosts")}
}

func (_c *MockRemoteHostStore_Hosts_Call) Run(run func()) *MockRemoteHostStore_Hosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRemoteHostStore_Hosts_Call) Return(pinned []string, learned []string, err error) *MockRemoteHostStore_Hosts_Call {
	_c.Call.Return(pinned, learned, err)
	return _c
}

func (_c *MockRemoteHostStore_Hosts_Call) RunAndReturn(run func() ([]string, []string, error)) *MockRemoteHostStore_Hosts_Call {
	_c.Call.Return(run)
	return _c
}

// Remember provides a mock function for the type MockRemoteHostStore
func (_mock *MockRemoteHostStore) Remember(target string) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Remember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRemoteHostStore_Remember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remember'
type MockRemoteHostStore_Remember_Call struct {
	*mock.Call
}

// Remember is a helper method to define mock.On call
//   - target string
func (_e *MockRemoteHostStore_Expecter) Remember(target any) *MockRemoteHostStore_Remember_Call {
	return &MockRemoteHostStore_Remember_Call{Call: _e.mock.On("Remember", target)}
}

func (_c *MockRemoteHostStore_Remember_Call) Run(run func(target string)) *MockRemoteHostStore_Remember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRemoteHostStore_Remember_Call) Return(err error) *MockRemoteHostStore_Remember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRemoteHostStore_Remember_Call) RunAndReturn(run func(target string) error) *MockRemoteHostStore_Remember_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockRemoteHostStore
func (_mock *MockRemoteHostStore) Remove(target string) (bool, error) {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(target)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRemoteHostStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockRemoteHostStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - target string
func (_e *MockRemoteHostStore_Expecter) Remove(target any) *MockRemoteHostStore_Remove_Call {
	return &MockRemoteHostStore_Remove_Call{Call: _e.mock.On("Remove", target)}
}

func (_c *MockRemoteHostStore_Remove_Call) Run(run func(target string)) *MockRemoteHostStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRemoteHostStore_Remove_Call) Return(deleted bool, err error) *MockRemoteHostStore_Remove_Call {
	_c.Call.Return(deleted, err)
	return _c
}

func (_c *MockRemoteHostStore_Remove_Call) RunAndReturn(run func(target string) (bool, error)) *MockRemoteHostStore_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePinned provides a mock function for the type MockRemoteHostStore
func (_mock *MockRemoteHostStore) RemovePinned(target string) error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for RemovePinned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRemoteHostStore_RemovePinned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePinned'
type MockRemoteHostStore_RemovePinned_Call struct {
	*mock.Call
}

// RemovePinned is a helper method to define mock.On call
//   - target string
func (_e *MockRemoteHostStore_Expecter) RemovePinned(target any) *MockRemoteHostStore_RemovePinned_Call {
	return &MockRemoteHostStore_RemovePinned_Call{Call: _e.mock.On("RemovePinned", target)}
}

func (_c *MockRemoteHostStore_RemovePinned_Call) Run(run func(target string)) *MockRemoteHostStore_RemovePinned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRemoteHostStore_RemovePinned_Call) Return(err error) *MockRemoteHostStore_RemovePinned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRemoteHostStore_RemovePinned_Call) RunAndReturn(run func(target string) error) *MockRemoteHostStore_RemovePinned_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRemoteHostLearner creates a new instance of MockRemoteHostLearner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteHostLearner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteHostLearner {
	mock := &MockRemoteHostLearner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRemoteHostLearner is an autogenerated mock type for the RemoteHostLearner type
type MockRemoteHostLearner struct {
	mock.Mock
}

type MockRemoteHostLearner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteHostLearner) EXPECT() *MockRemoteHostLearner_Expecter {
	return &MockRemoteHostLearner_Expecter{mock: &_m.Mock}
}

// RememberRemoteHost provides a mock function for the type MockRemoteHostLearner
func (_mock *MockRemoteHostLearner) RememberRemoteHost() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RememberRemoteHost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRemoteHostLearner_RememberRemoteHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RememberRemoteHost'
type MockRemoteHostLearner_RememberRemoteHost_Call struct {
	*mock.Call
}

// RememberRemoteHost is a helper method to define mock.On call
func (_e *MockRemoteHostLearner_Expecter) RememberRemoteHost() *MockRemoteHostLearner_RememberRemoteHost_Call {
	return &MockRemoteHostLearner_RememberRemoteHost_Call{Call: _e.mock.On("RememberRemoteHost")}
}

func (_c *MockRemoteHostLearner_RememberRemoteHost_Call) Run(run func()) *MockRemoteHostLearner_RememberRemoteHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRemoteHostLearner_RememberRemoteHost_Call) Return(err error) *MockRemoteHostLearner_RememberRemoteHost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRemoteHostLearner_RememberRemoteHost_Call) RunAndReturn(run func() error) *MockRemoteHostLearner_RememberRemoteHost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRemoteCatalogClient creates a new instance of MockRemoteCatalogClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteCatalogClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteCatalogClient {
	mock := &MockRemoteCatalogClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRemoteCatalogClient is an autogenerated mock type for the RemoteCatalogClient type
type MockRemoteCatalogClient struct {
	mock.Mock
}

type MockRemoteCatalogClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteCatalogClient) EXPECT() *MockRemoteCatalogClient_Expecter {
	return &MockRemoteCatalogClient_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockRemoteCatalogClient
func (_mock *MockRemoteCatalogClient) List(ctx context.Context, target string) (ports.RemoteCatalog, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 ports.RemoteCatalog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.RemoteCatalog, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.RemoteCatalog); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Get(0).(ports.RemoteCatalog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRemoteCatalogClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRemoteCatalogClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockRemoteCatalogClient_Expecter) List(ctx any, target any) *MockRemoteCatalogClient_List_Call {
	return &MockRemoteCatalogClient_List_Call{Call: _e.mock.On("List", ctx, target)}
}

func (_c *MockRemoteCatalogClient_List_Call) Run(run func(ctx context.Context, target string)) *MockRemoteCatalogClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRemoteCatalogClient_List_Call) Return(remoteCatalog ports.RemoteCatalog, err error) *MockRemoteCatalogClient_List_Call {
	_c.Call.Return(remoteCatalog, err)
	return _c
}

func (_c *MockRemoteCatalogClient_List_Call) RunAndReturn(run func(ctx context.Context, target string) (ports.RemoteCatalog, error)) *MockRemoteCatalogClient_List_Call {
	_c.Call.Return(run)
	return _c
}
