// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/bnema/vev/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Batch provides a mock function for the type MockStore
func (_mock *MockStore) Batch(storeChanges []ports.StoreChange) error {
	ret := _mock.Called(storeChanges)

	if len(ret) == 0 {
		panic("no return value specified for Batch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]ports.StoreChange) error); ok {
		r0 = returnFunc(storeChanges)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Batch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Batch'
type MockStore_Batch_Call struct {
	*mock.Call
}

// Batch is a helper method to define mock.On call
//   - storeChanges []ports.StoreChange
func (_e *MockStore_Expecter) Batch(storeChanges any) *MockStore_Batch_Call {
	return &MockStore_Batch_Call{Call: _e.mock.On("Batch", storeChanges)}
}

func (_c *MockStore_Batch_Call) Run(run func(storeChanges []ports.StoreChange)) *MockStore_Batch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []ports.StoreChange
		if args[0] != nil {
			arg0 = args[0].([]ports.StoreChange)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Batch_Call) Return(err error) *MockStore_Batch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Batch_Call) RunAndReturn(run func(storeChanges []ports.StoreChange) error) *MockStore_Batch_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockStore
func (_mock *MockStore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(err error) *MockStore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStore
func (_mock *MockStore) Delete(key []byte) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key []byte
func (_e *MockStore_Expecter) Delete(key any) *MockStore_Delete_Call {
	return &MockStore_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockStore_Delete_Call) Run(run func(key []byte)) *MockStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Delete_Call) Return(err error) *MockStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Delete_Call) RunAndReturn(run func(key []byte) error) *MockStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStore
func (_mock *MockStore) Get(key []byte) ([]byte, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key []byte
func (_e *MockStore_Expecter) Get(key any) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockStore_Get_Call) Run(run func(key []byte)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(bytes []byte, b bool) *MockStore_Get_Call {
	_c.Call.Return(bytes, b)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(key []byte) ([]byte, bool)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Range provides a mock function for the type MockStore
func (_mock *MockStore) Range(fn func(k []byte, v []byte) bool) {
	_mock.Called(fn)
	return
}

// MockStore_Range_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Range'
type MockStore_Range_Call struct {
	*mock.Call
}

// Range is a helper method to define mock.On call
//   - fn func(k []byte, v []byte) bool
func (_e *MockStore_Expecter) Range(fn any) *MockStore_Range_Call {
	return &MockStore_Range_Call{Call: _e.mock.On("Range", fn)}
}

func (_c *MockStore_Range_Call) Run(run func(fn func(k []byte, v []byte) bool)) *MockStore_Range_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(k []byte, v []byte) bool
		if args[0] != nil {
			arg0 = args[0].(func(k []byte, v []byte) bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Range_Call) Return() *MockStore_Range_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStore_Range_Call) RunAndReturn(run func(fn func(k []byte, v []byte) bool)) *MockStore_Range_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type MockStore
func (_mock *MockStore) Set(key []byte, val []byte) error {
	ret := _mock.Called(key, val)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = returnFunc(key, val)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key []byte
//   - val []byte
func (_e *MockStore_Expecter) Set(key any, val any) *MockStore_Set_Call {
	return &MockStore_Set_Call{Call: _e.mock.On("Set", key, val)}
}

func (_c *MockStore_Set_Call) Run(run func(key []byte, val []byte)) *MockStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Set_Call) Return(err error) *MockStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Set_Call) RunAndReturn(run func(key []byte, val []byte) error) *MockStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockStore
func (_mock *MockStore) Sync() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockStore_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
func (_e *MockStore_Expecter) Sync() *MockStore_Sync_Call {
	return &MockStore_Sync_Call{Call: _e.mock.On("Sync")}
}

func (_c *MockStore_Sync_Call) Run(run func()) *MockStore_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Sync_Call) Return(err error) *MockStore_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Sync_Call) RunAndReturn(run func() error) *MockStore_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLegacySnapshotSource creates a new instance of MockLegacySnapshotSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLegacySnapshotSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLegacySnapshotSource {
	mock := &MockLegacySnapshotSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLegacySnapshotSource is an autogenerated mock type for the LegacySnapshotSource type
type MockLegacySnapshotSource struct {
	mock.Mock
}

type MockLegacySnapshotSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLegacySnapshotSource) EXPECT() *MockLegacySnapshotSource_Expecter {
	return &MockLegacySnapshotSource_Expecter{mock: &_m.Mock}
}

// DeleteLegacy provides a mock function for the type MockLegacySnapshotSource
func (_mock *MockLegacySnapshotSource) DeleteLegacy(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLegacy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLegacySnapshotSource_DeleteLegacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLegacy'
type MockLegacySnapshotSource_DeleteLegacy_Call struct {
	*mock.Call
}

// DeleteLegacy is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockLegacySnapshotSource_Expecter) DeleteLegacy(context1 any, s any) *MockLegacySnapshotSource_DeleteLegacy_Call {
	return &MockLegacySnapshotSource_DeleteLegacy_Call{Call: _e.mock.On("DeleteLegacy", context1, s)}
}

func (_c *MockLegacySnapshotSource_DeleteLegacy_Call) Run(run func(context1 context.Context, s string)) *MockLegacySnapshotSource_DeleteLegacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLegacySnapshotSource_DeleteLegacy_Call) Return(err error) *MockLegacySnapshotSource_DeleteLegacy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLegacySnapshotSource_DeleteLegacy_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockLegacySnapshotSource_DeleteLegacy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerifiedLegacy provides a mock function for the type MockLegacySnapshotSource
func (_mock *MockLegacySnapshotSource) DeleteVerifiedLegacy(context1 context.Context, legacySnapshot ports.LegacySnapshot) error {
	ret := _mock.Called(context1, legacySnapshot)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerifiedLegacy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.LegacySnapshot) error); ok {
		r0 = returnFunc(context1, legacySnapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLegacySnapshotSource_DeleteVerifiedLegacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerifiedLegacy'
type MockLegacySnapshotSource_DeleteVerifiedLegacy_Call struct {
	*mock.Call
}

// DeleteVerifiedLegacy is a helper method to define mock.On call
//   - context1 context.Context
//   - legacySnapshot ports.LegacySnapshot
func (_e *MockLegacySnapshotSource_Expecter) DeleteVerifiedLegacy(context1 any, legacySnapshot any) *MockLegacySnapshotSource_DeleteVerifiedLegacy_Call {
	return &MockLegacySnapshotSource_DeleteVerifiedLegacy_Call{Call: _e.mock.On("DeleteVerifiedLegacy", context1, legacySnapshot)}
}

func (_c *MockLegacySnapshotSource_DeleteVerifiedLegacy_Call) Run(run func(context1 context.Context, legacySnapshot ports.LegacySnapshot)) *MockLegacySnapshotSource_DeleteVerifiedLegacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.LegacySnapshot
		if args[1] != nil {
			arg1 = args[1].(ports.LegacySnapshot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLegacySnapshotSource_DeleteVerifiedLegacy_Call) Return(err error) *MockLegacySnapshotSource_DeleteVerifiedLegacy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLegacySnapshotSource_DeleteVerifiedLegacy_Call) RunAndReturn(run func(context1 context.Context, legacySnapshot ports.LegacySnapshot) error) *MockLegacySnapshotSource_DeleteVerifiedLegacy_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLegacy provides a mock function for the type MockLegacySnapshotSource
func (_mock *MockLegacySnapshotSource) LoadLegacy(context1 context.Context) ([]ports.LegacySnapshot, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for LoadLegacy")
	}

	var r0 []ports.LegacySnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.LegacySnapshot, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.LegacySnapshot); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.LegacySnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLegacySnapshotSource_LoadLegacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLegacy'
type MockLegacySnapshotSource_LoadLegacy_Call struct {
	*mock.Call
}

// LoadLegacy is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockLegacySnapshotSource_Expecter) LoadLegacy(context1 any) *MockLegacySnapshotSource_LoadLegacy_Call {
	return &MockLegacySnapshotSource_LoadLegacy_Call{Call: _e.mock.On("LoadLegacy", context1)}
}

func (_c *MockLegacySnapshotSource_LoadLegacy_Call) Run(run func(context1 context.Context)) *MockLegacySnapshotSource_LoadLegacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLegacySnapshotSource_LoadLegacy_Call) Return(legacySnapshots []ports.LegacySnapshot, err error) *MockLegacySnapshotSource_LoadLegacy_Call {
	_c.Call.Return(legacySnapshots, err)
	return _c
}

func (_c *MockLegacySnapshotSource_LoadLegacy_Call) RunAndReturn(run func(context1 context.Context) ([]ports.LegacySnapshot, error)) *MockLegacySnapshotSource_LoadLegacy_Call {
	_c.Call.Return(run)
	return _c
}
