// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"io"

	"github.com/bnema/vev/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTerminal creates a new instance of MockTerminal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTerminal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTerminal {
	mock := &MockTerminal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTerminal is an autogenerated mock type for the Terminal type
type MockTerminal struct {
	mock.Mock
}

type MockTerminal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTerminal) EXPECT() *MockTerminal_Expecter {
	return &MockTerminal_Expecter{mock: &_m.Mock}
}

// EnterRaw provides a mock function for the type MockTerminal
func (_mock *MockTerminal) EnterRaw() (func() error, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnterRaw")
	}

	var r0 func() error
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (func() error, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() func() error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTerminal_EnterRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnterRaw'
type MockTerminal_EnterRaw_Call struct {
	*mock.Call
}

// EnterRaw is a helper method to define mock.On call
func (_e *MockTerminal_Expecter) EnterRaw() *MockTerminal_EnterRaw_Call {
	return &MockTerminal_EnterRaw_Call{Call: _e.mock.On("EnterRaw")}
}

func (_c *MockTerminal_EnterRaw_Call) Run(run func()) *MockTerminal_EnterRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminal_EnterRaw_Call) Return(restore func() error, err error) *MockTerminal_EnterRaw_Call {
	_c.Call.Return(restore, err)
	return _c
}

func (_c *MockTerminal_EnterRaw_Call) RunAndReturn(run func() (func() error, error)) *MockTerminal_EnterRaw_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function for the type MockTerminal
func (_mock *MockTerminal) Flush() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTerminal_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockTerminal_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
func (_e *MockTerminal_Expecter) Flush() *MockTerminal_Flush_Call {
	return &MockTerminal_Flush_Call{Call: _e.mock.On("Flush")}
}

func (_c *MockTerminal_Flush_Call) Run(run func()) *MockTerminal_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminal_Flush_Call) Return(err error) *MockTerminal_Flush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTerminal_Flush_Call) RunAndReturn(run func() error) *MockTerminal_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Geometry provides a mock function for the type MockTerminal
func (_mock *MockTerminal) Geometry() (domain.Geometry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Geometry")
	}

	var r0 domain.Geometry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (domain.Geometry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() domain.Geometry); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.Geometry)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTerminal_Geometry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Geometry'
type MockTerminal_Geometry_Call struct {
	*mock.Call
}

// Geometry is a helper method to define mock.On call
func (_e *MockTerminal_Expecter) Geometry() *MockTerminal_Geometry_Call {
	return &MockTerminal_Geometry_Call{Call: _e.mock.On("Geometry")}
}

func (_c *MockTerminal_Geometry_Call) Run(run func()) *MockTerminal_Geometry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminal_Geometry_Call) Return(geometry domain.Geometry, err error) *MockTerminal_Geometry_Call {
	_c.Call.Return(geometry, err)
	return _c
}

func (_c *MockTerminal_Geometry_Call) RunAndReturn(run func() (domain.Geometry, error)) *MockTerminal_Geometry_Call {
	_c.Call.Return(run)
	return _c
}

// In provides a mock function for the type MockTerminal
func (_mock *MockTerminal) In() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for In")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// MockTerminal_In_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'In'
type MockTerminal_In_Call struct {
	*mock.Call
}

// In is a helper method to define mock.On call
func (_e *MockTerminal_Expecter) In() *MockTerminal_In_Call {
	return &MockTerminal_In_Call{Call: _e.mock.On("In")}
}

func (_c *MockTerminal_In_Call) Run(run func()) *MockTerminal_In_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminal_In_Call) Return(reader io.Reader) *MockTerminal_In_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockTerminal_In_Call) RunAndReturn(run func() io.Reader) *MockTerminal_In_Call {
	_c.Call.Return(run)
	return _c
}

// Out provides a mock function for the type MockTerminal
func (_mock *MockTerminal) Out() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Out")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockTerminal_Out_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Out'
type MockTerminal_Out_Call struct {
	*mock.Call
}

// Out is a helper method to define mock.On call
func (_e *MockTerminal_Expecter) Out() *MockTerminal_Out_Call {
	return &MockTerminal_Out_Call{Call: _e.mock.On("Out")}
}

func (_c *MockTerminal_Out_Call) Run(run func()) *MockTerminal_Out_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminal_Out_Call) Return(writer io.Writer) *MockTerminal_Out_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockTerminal_Out_Call) RunAndReturn(run func() io.Writer) *MockTerminal_Out_Call {
	_c.Call.Return(run)
	return _c
}

// ResizeEvents provides a mock function for the type MockTerminal
func (_mock *MockTerminal) ResizeEvents() <-chan domain.Geometry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResizeEvents")
	}

	var r0 <-chan domain.Geometry
	if returnFunc, ok := ret.Get(0).(func() <-chan domain.Geometry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.Geometry)
		}
	}
	return r0
}

// MockTerminal_ResizeEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeEvents'
type MockTerminal_ResizeEvents_Call struct {
	*mock.Call
}

// ResizeEvents is a helper method to define mock.On call
func (_e *MockTerminal_Expecter) ResizeEvents() *MockTerminal_ResizeEvents_Call {
	return &MockTerminal_ResizeEvents_Call{Call: _e.mock.On("ResizeEvents")}
}

func (_c *MockTerminal_ResizeEvents_Call) Run(run func()) *MockTerminal_ResizeEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminal_ResizeEvents_Call) Return(geometryCh <-chan domain.Geometry) *MockTerminal_ResizeEvents_Call {
	_c.Call.Return(geometryCh)
	return _c
}

func (_c *MockTerminal_ResizeEvents_Call) RunAndReturn(run func() <-chan domain.Geometry) *MockTerminal_ResizeEvents_Call {
	_c.Call.Return(run)
	return _c
}
