// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"github.com/bnema/vev/internal/domain"
	"github.com/bnema/vev/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUIObservationSink creates a new instance of MockUIObservationSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUIObservationSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUIObservationSink {
	mock := &MockUIObservationSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUIObservationSink is an autogenerated mock type for the UIObservationSink type
type MockUIObservationSink struct {
	mock.Mock
}

type MockUIObservationSink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUIObservationSink) EXPECT() *MockUIObservationSink_Expecter {
	return &MockUIObservationSink_Expecter{mock: &_m.Mock}
}

// InvalidateTerminalObservation provides a mock function for the type MockUIObservationSink
func (_mock *MockUIObservationSink) InvalidateTerminalObservation() {
	_mock.Called()
	return
}

// MockUIObservationSink_InvalidateTerminalObservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateTerminalObservation'
type MockUIObservationSink_InvalidateTerminalObservation_Call struct {
	*mock.Call
}

// InvalidateTerminalObservation is a helper method to define mock.On call
func (_e *MockUIObservationSink_Expecter) InvalidateTerminalObservation() *MockUIObservationSink_InvalidateTerminalObservation_Call {
	return &MockUIObservationSink_InvalidateTerminalObservation_Call{Call: _e.mock.On("InvalidateTerminalObservation")}
}

func (_c *MockUIObservationSink_InvalidateTerminalObservation_Call) Run(run func()) *MockUIObservationSink_InvalidateTerminalObservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUIObservationSink_InvalidateTerminalObservation_Call) Return() *MockUIObservationSink_InvalidateTerminalObservation_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUIObservationSink_InvalidateTerminalObservation_Call) RunAndReturn(run func()) *MockUIObservationSink_InvalidateTerminalObservation_Call {
	_c.Run(run)
	return _c
}

// ObserveTerminalFlush provides a mock function for the type MockUIObservationSink
func (_mock *MockUIObservationSink) ObserveTerminalFlush() {
	_mock.Called()
	return
}

// MockUIObservationSink_ObserveTerminalFlush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveTerminalFlush'
type MockUIObservationSink_ObserveTerminalFlush_Call struct {
	*mock.Call
}

// ObserveTerminalFlush is a helper method to define mock.On call
func (_e *MockUIObservationSink_Expecter) ObserveTerminalFlush() *MockUIObservationSink_ObserveTerminalFlush_Call {
	return &MockUIObservationSink_ObserveTerminalFlush_Call{Call: _e.mock.On("ObserveTerminalFlush")}
}

func (_c *MockUIObservationSink_ObserveTerminalFlush_Call) Run(run func()) *MockUIObservationSink_ObserveTerminalFlush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUIObservationSink_ObserveTerminalFlush_Call) Return() *MockUIObservationSink_ObserveTerminalFlush_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUIObservationSink_ObserveTerminalFlush_Call) RunAndReturn(run func()) *MockUIObservationSink_ObserveTerminalFlush_Call {
	_c.Run(run)
	return _c
}

// ObserveTerminalResize provides a mock function for the type MockUIObservationSink
func (_mock *MockUIObservationSink) ObserveTerminalResize(geometry domain.Geometry) {
	_mock.Called(geometry)
	return
}

// MockUIObservationSink_ObserveTerminalResize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveTerminalResize'
type MockUIObservationSink_ObserveTerminalResize_Call struct {
	*mock.Call
}

// ObserveTerminalResize is a helper method to define mock.On call
//   - geometry domain.Geometry
func (_e *MockUIObservationSink_Expecter) ObserveTerminalResize(geometry any) *MockUIObservationSink_ObserveTerminalResize_Call {
	return &MockUIObservationSink_ObserveTerminalResize_Call{Call: _e.mock.On("ObserveTerminalResize", geometry)}
}

func (_c *MockUIObservationSink_ObserveTerminalResize_Call) Run(run func(geometry domain.Geometry)) *MockUIObservationSink_ObserveTerminalResize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Geometry
		if args[0] != nil {
			arg0 = args[0].(domain.Geometry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUIObservationSink_ObserveTerminalResize_Call) Return() *MockUIObservationSink_ObserveTerminalResize_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUIObservationSink_ObserveTerminalResize_Call) RunAndReturn(run func(geometry domain.Geometry)) *MockUIObservationSink_ObserveTerminalResize_Call {
	_c.Run(run)
	return _c
}

// ObserveTerminalWrite provides a mock function for the type MockUIObservationSink
func (_mock *MockUIObservationSink) ObserveTerminalWrite(data []byte) {
	_mock.Called(data)
	return
}

// MockUIObservationSink_ObserveTerminalWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveTerminalWrite'
type MockUIObservationSink_ObserveTerminalWrite_Call struct {
	*mock.Call
}

// ObserveTerminalWrite is a helper method to define mock.On call
//   - data []byte
func (_e *MockUIObservationSink_Expecter) ObserveTerminalWrite(data any) *MockUIObservationSink_ObserveTerminalWrite_Call {
	return &MockUIObservationSink_ObserveTerminalWrite_Call{Call: _e.mock.On("ObserveTerminalWrite", data)}
}

func (_c *MockUIObservationSink_ObserveTerminalWrite_Call) Run(run func(data []byte)) *MockUIObservationSink_ObserveTerminalWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUIObservationSink_ObserveTerminalWrite_Call) Return() *MockUIObservationSink_ObserveTerminalWrite_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUIObservationSink_ObserveTerminalWrite_Call) RunAndReturn(run func(data []byte)) *MockUIObservationSink_ObserveTerminalWrite_Call {
	_c.Run(run)
	return _c
}

// NewMockUIOutputTransaction creates a new instance of MockUIOutputTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUIOutputTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUIOutputTransaction {
	mock := &MockUIOutputTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUIOutputTransaction is an autogenerated mock type for the UIOutputTransaction type
type MockUIOutputTransaction struct {
	mock.Mock
}

type MockUIOutputTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUIOutputTransaction) EXPECT() *MockUIOutputTransaction_Expecter {
	return &MockUIOutputTransaction_Expecter{mock: &_m.Mock}
}

// BeginOutput provides a mock function for the type MockUIOutputTransaction
func (_mock *MockUIOutputTransaction) BeginOutput(context ports.UIContext) {
	_mock.Called(context)
	return
}

// MockUIOutputTransaction_BeginOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginOutput'
type MockUIOutputTransaction_BeginOutput_Call struct {
	*mock.Call
}

// BeginOutput is a helper method to define mock.On call
//   - context ports.UIContext
func (_e *MockUIOutputTransaction_Expecter) BeginOutput(context any) *MockUIOutputTransaction_BeginOutput_Call {
	return &MockUIOutputTransaction_BeginOutput_Call{Call: _e.mock.On("BeginOutput", context)}
}

func (_c *MockUIOutputTransaction_BeginOutput_Call) Run(run func(context ports.UIContext)) *MockUIOutputTransaction_BeginOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.UIContext
		if args[0] != nil {
			arg0 = args[0].(ports.UIContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUIOutputTransaction_BeginOutput_Call) Return() *MockUIOutputTransaction_BeginOutput_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUIOutputTransaction_BeginOutput_Call) RunAndReturn(run func(context ports.UIContext)) *MockUIOutputTransaction_BeginOutput_Call {
	_c.Run(run)
	return _c
}

// EndOutput provides a mock function for the type MockUIOutputTransaction
func (_mock *MockUIOutputTransaction) EndOutput(success bool) {
	_mock.Called(success)
	return
}

// MockUIOutputTransaction_EndOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndOutput'
type MockUIOutputTransaction_EndOutput_Call struct {
	*mock.Call
}

// EndOutput is a helper method to define mock.On call
//   - success bool
func (_e *MockUIOutputTransaction_Expecter) EndOutput(success any) *MockUIOutputTransaction_EndOutput_Call {
	return &MockUIOutputTransaction_EndOutput_Call{Call: _e.mock.On("EndOutput", success)}
}

func (_c *MockUIOutputTransaction_EndOutput_Call) Run(run func(success bool)) *MockUIOutputTransaction_EndOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUIOutputTransaction_EndOutput_Call) Return() *MockUIOutputTransaction_EndOutput_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUIOutputTransaction_EndOutput_Call) RunAndReturn(run func(success bool)) *MockUIOutputTransaction_EndOutput_Call {
	_c.Run(run)
	return _c
}

// PublishContext provides a mock function for the type MockUIOutputTransaction
func (_mock *MockUIOutputTransaction) PublishContext(context ports.UIContext) error {
	ret := _mock.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for PublishContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ports.UIContext) error); ok {
		r0 = returnFunc(context)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUIOutputTransaction_PublishContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishContext'
type MockUIOutputTransaction_PublishContext_Call struct {
	*mock.Call
}

// PublishContext is a helper method to define mock.On call
//   - context ports.UIContext
func (_e *MockUIOutputTransaction_Expecter) PublishContext(context any) *MockUIOutputTransaction_PublishContext_Call {
	return &MockUIOutputTransaction_PublishContext_Call{Call: _e.mock.On("PublishContext", context)}
}

func (_c *MockUIOutputTransaction_PublishContext_Call) Run(run func(context ports.UIContext)) *MockUIOutputTransaction_PublishContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.UIContext
		if args[0] != nil {
			arg0 = args[0].(ports.UIContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUIOutputTransaction_PublishContext_Call) Return(err error) *MockUIOutputTransaction_PublishContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUIOutputTransaction_PublishContext_Call) RunAndReturn(run func(context ports.UIContext) error) *MockUIOutputTransaction_PublishContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUIState creates a new instance of MockUIState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUIState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUIState {
	mock := &MockUIState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUIState is an autogenerated mock type for the UIState type
type MockUIState struct {
	mock.Mock
}

type MockUIState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUIState) EXPECT() *MockUIState_Expecter {
	return &MockUIState_Expecter{mock: &_m.Mock}
}

// Changes provides a mock function for the type MockUIState
func (_mock *MockUIState) Changes() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Changes")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockUIState_Changes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Changes'
type MockUIState_Changes_Call struct {
	*mock.Call
}

// Changes is a helper method to define mock.On call
func (_e *MockUIState_Expecter) Changes() *MockUIState_Changes_Call {
	return &MockUIState_Changes_Call{Call: _e.mock.On("Changes")}
}

func (_c *MockUIState_Changes_Call) Run(run func()) *MockUIState_Changes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUIState_Changes_Call) Return(valCh <-chan struct{}) *MockUIState_Changes_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockUIState_Changes_Call) RunAndReturn(run func() <-chan struct{}) *MockUIState_Changes_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type MockUIState
func (_mock *MockUIState) Snapshot() (ports.UISnapshot, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 ports.UISnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (ports.UISnapshot, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() ports.UISnapshot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.UISnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUIState_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockUIState_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockUIState_Expecter) Snapshot() *MockUIState_Snapshot_Call {
	return &MockUIState_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockUIState_Snapshot_Call) Run(run func()) *MockUIState_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUIState_Snapshot_Call) Return(uISnapshot ports.UISnapshot, err error) *MockUIState_Snapshot_Call {
	_c.Call.Return(uISnapshot, err)
	return _c
}

func (_c *MockUIState_Snapshot_Call) RunAndReturn(run func() (ports.UISnapshot, error)) *MockUIState_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}
